'\" t
.\"     Title: shorewall-exclusion
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 10/02/2010
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "SHOREWALL\-EXCLUSION" "5" "10/02/2010" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
exclusion \- Exclude a set of hosts from a definition in a shorewall configuration file\&.
.SH "SYNOPSIS"
.HP \w'\ 'u
\fB!\fR\fIaddress\-or\-range\fR[,\fIaddress\-or\-range\fR]...
.SH "DESCRIPTION"
.PP
Exclusion is used when you wish to exclude one or more addresses from a definition\&. An exclaimation point is followed by a comma\-separated list of addresses\&. The addresses may be single host addresses (e\&.g\&., 192\&.168\&.1\&.4) or they may be network addresses in CIDR format (e\&.g\&., 192\&.168\&.1\&.0/24)\&. If your kernel and iptables include iprange support, you may also specify ranges of ip addresses of the form
\fIlowaddress\fR\-\fIhighaddress\fR
.PP
No embedded whitespace is allowed\&.
.PP
Exclusion can appear after a list of addresses and/or address ranges\&. In that case, the final list of address is formed by taking the first list and then removing the addresses defined in the exclusion\&.
.SH "EXAMPLES"
.PP
Example 1 \- All IPv4 addresses except 192\&.168\&.3\&.4
.RS 4
!192\&.168\&.3\&.4
.RE
.PP
Example 2 \- All IPv4 addresses except the network 192\&.168\&.1\&.0/24 and the host 10\&.2\&.3\&.4
.RS 4
!192\&.168\&.1\&.0/24,10\&.1\&.3\&.4
.RE
.PP
Example 3 \- All IPv4 addresses except the range 192\&.168\&.1\&.3\-192\&.168\&.1\&.12 and the network 10\&.0\&.0\&.0/8
.RS 4
!192\&.168\&.1\&.3\-192\&.168\&.1\&.12,10\&.0\&.0\&.0/8
.RE
.PP
Example 4 \- The network 192\&.168\&.1\&.0/24 except hosts 192\&.168\&.1\&.3 and 192\&.168\&.1\&.9
.RS 4
192\&.168\&.1\&.0/24!192\&.168\&.1\&.3,192\&.168\&.1\&.9
.RE
.SH "FILES"
.PP
/etc/shorewall/hosts
.PP
/etc/shorewall/masq
.PP
/etc/shorewall/rules
.PP
/etc/shorewall/tcrules
.SH "SEE ALSO"
.PP
shorewall(8), shorewall\-accounting(5), shorewall\-actions(5), shorewall\-blacklist(5), shorewall\-hosts(5), shorewall\-interfaces(5), shorewall\-ipsec(5), shorewall\-maclist(5), shorewall\-masq(5), shorewall\-nat(5), shorewall\-netmap(5), shorewall\-params(5), shorewall\-policy(5), shorewall\-providers(5), shorewall\-proxyarp(5), shorewall\-route_rules(5), shorewall\-routestopped(5), shorewall\-rules(5), shorewall\&.conf(5), shorewall\-tcclasses(5), shorewall\-tcdevices(5), shorewall\-tcrules(5), shorewall\-tos(5), shorewall\-tunnels(5), shorewall\-zones(5)
