'\" t
.\"     Title: shorewall6-tos
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 08/20/2011
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "SHOREWALL6\-TOS" "5" "08/20/2011" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
tos \- Shorewall6 Type of Service rules file
.SH "SYNOPSIS"
.HP \w'\fB/etc/shorewall6/tos\fR\ 'u
\fB/etc/shorewall6/tos\fR
.SH "DESCRIPTION"
.PP
This file defines rules for setting Type Of Service (TOS)
.PP
The columns in the file are as follows\&.
.PP
\fBSOURCE\fR \- {\fBall\fR|\fIaddress\fR]|\fBall\fR:\fIaddress\fR|\fB$FW\fR}
.RS 4
If
\fBall\fR, may optionally be followed by ":" and an IP address, a MAC address, a subnet specification or the name of an interface\&.
.sp
Example: all:2002:ce7c::92b4:1::2
.sp
MAC addresses must be prefixed with "~" and use "\-" as a separator\&.
.sp
Example: ~00\-A0\-C9\-15\-39\-78
.RE
.PP
\fBDEST\fR \- {\fBall\fR|\fIaddress\fR]|\fBall\fR:\fIaddress\fR}
.RS 4
Example: 2002:ce7c::92b4:1::2
.RE
.PP
\fBPROTOCOL\fR \- \fIproto\-name\-or\-number\fR
.RS 4
Protocol name or number\&.
.RE
.PP
\fBSOURCE PORT(S)\fR \- {\-|\fIport\fR|\fIlowport\fR\fB:\fR\fIhighport\fR}
.RS 4
Source port or port range\&. If all ports, use "\-"\&.
.RE
.PP
\fBDEST PORT(S)\fR \- {\-|\fIport\fR|\fIlowport\fR\fB:\fR\fIhighport\fR}
.RS 4
Destination port or port range\&. If all ports, use "\-"
.RE
.PP
\fBTOS\fR \- \fItos\fR
.RS 4
Must be one of the following;
.sp
.if n \{\
.RS 4
.\}
.nf
        \fBtos\-minimize\-delay\fR (16)
        \fBtos\-maximize\-throughput\fR (8)
        \fBtos\-maximize\-reliability\fR (4)
        \fBtos\-minimize\-cost\fR (2)
        \fBtos\-normal\-service\fR (0)
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBMARK\fR \- [\fB!\fR]\fIvalue\fR[/\fImask\fR][\fB:C\fR]
.RS 4
If you don\*(Aqt want to define a test but need to specify anything in the following columns, place a "\-" in this field\&.
.PP
!
.RS 4
Inverts the test (not equal)
.RE
.PP
\fIvalue\fR
.RS 4
Value of the packet or connection mark\&.
.RE
.PP
\fImask\fR
.RS 4
A mask to be applied to the mark before testing\&.
.RE
.PP
\fB:C\fR
.RS 4
Designates a connection mark\&. If omitted, the packet mark\*(Aqs value is tested\&.
.RE
.RE
.SH "FILES"
.PP
/etc/shorewall6/tos
.SH "SEE ALSO"
.PP
shorewall6(8), shorewall6\-accounting(5), shorewall6\-actions(5), shorewall6\-blacklist(5), shorewall6\-hosts(5), shorewall6\-interfaces(5), shorewall6\-maclist(5), shorewall6\-params(5), shorewall6\-policy(5), shorewall6\-providers(5), shorewall6\-route_rules(5), shorewall6\-routestopped(5), shorewall6\-rules(5), shorewall6\&.conf(5), shorewall6\-secmarks(5), shorewall6\-tcclasses(5), shorewall6\-tcdevices(5), shorewall6\-tcrules(5), shorewall6\-tunnels(5), shorewall6\-zones(5)
