'\" t
.\"     Title: shorewall6.conf
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 10/21/2013
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "SHOREWALL6\&.CONF" "5" "10/21/2013" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
shorewall6.conf \- Shorewall6 global configuration file
.SH "SYNOPSIS"
.HP \w'\fB/etc/shorewall6/shorewall6\&.conf\fR\ 'u
\fB/etc/shorewall6/shorewall6\&.conf\fR
.SH "DESCRIPTION"
.PP
This file sets options that apply to Shorewall6 as a whole\&.
.PP
The file consists of Shell comments (lines beginning with \*(Aq#\*(Aq), blank lines and assignment statements (\fIvariable\fR=\fIvalue\fR)\&. If the
\fIvalue\fR
contains shell meta characters or white\-space, then it must be enclosed in quotes\&. Example: LOG_LEVEL="NFLOG(1,0,1)"\&.
.SH "OPTIONS"
.PP
Many options have as their value a
\fIlog\-level\fR\&. Log levels are a method of describing to syslog (8) the importance of a message and a number of parameters in this file have log levels as their value\&.
.PP
These levels are defined by syslog and are used to determine the destination of the messages through entries in /etc/syslog\&.conf (5)\&. The syslog documentation refers to these as "priorities"; Netfilter calls them "levels" and Shorewall6 also uses that term\&.
.PP
Valid levels are:
.sp
.if n \{\
.RS 4
.\}
.nf
       7       debug
       6       info
       5       notice
       4       warning
       3       err
       2       crit
       1       alert
       0       emerg
.fi
.if n \{\
.RE
.\}
.PP
For most Shorewall6 logging, a level of 6 (info) is appropriate\&. Shorewall6 log messages are generated by NetFilter and are logged using facility \*(Aqkern\*(Aq and the level that you specify\&. If you are unsure of the level to choose, 6 (info) is a safe bet\&. You may specify levels by name or by number\&.
.PP
If you have built your kernel with NFLOG target support, you may also specify a log level of NFLOG (must be all caps)\&. Rather than log its messages to syslogd, Shorewall6 will direct netfilter to log the messages via the NFLOG target which will send them to a process called \*(Aqulogd\*(Aq\&. ulogd is available with most Linux distributions (although it probably isn\*(Aqt installed by default)\&. Ulogd is also available from
\m[blue]\fBhttp://www\&.netfilter\&.org/projects/ulogd/index\&.html\fR\m[]
and can be configured to log all Shorewall6 message to their own log file
.PP
The following options may be set in shorewall6\&.conf\&.
.PP
\fBACCEPT_DEFAULT=\fR{\fIaction\fR[(\fIparameters\fR)][:\fIlevel\fR]|\fBnone\fR}
.RS 4
.RE
.PP
\fBDROP_DEFAULT=\fR{\fIaction\fR[(\fIparameters\fR)][:\fIlevel\fR]|\fBnone\fR}
.RS 4
.RE
.PP
\fBNFQUEUE_DEFAULT=\fR{\fIaction\fR[(\fIparameters\fR)][:\fIlevel\fR]|\fBnone\fR}
.RS 4
.RE
.PP
\fBQUEUE_DEFAULT=\fR{\fIaction\fR[(\fIparameters\fR)][:\fIlevel\fR]|\fBnone\fR}
.RS 4
.RE
.PP
\fBREJECT_DEFAULT=\fR{\fIaction\fR[(\fIparameters\fR)][:\fIlevel\fR]|\fBnone\fR}
.RS 4
DROP_DEFAULT describes the rules to be applied before a connection request is dropped by a DROP policy; REJECT_DEFAULT describes the rules to be applied if a connection request is rejected by a REJECT policy\&. The other three are similar for ACCEPT, QUEUE and NFQUEUE policies\&.
.sp
The value applied to these may be:
.RS 4
a) The name of an \fIaction\fR\&. The
            name may optionally be followed by a comma\-separated list of
            parameters enclosed in parentheses if the specified action accepts
            parameters (e\&.g\&., \*(AqDrop(audit)\*(Aq)\&.
.RE
.RS 4
c) \fBNone\fR or \fBnone\fR
.RE
The default values are:
.RS 4
DROP_DEFAULT="Drop"
.RE
.RS 4
REJECT_DEFAULT="Reject"
.RE
.RS 4
ACCEPT_DEFAULT="none"
.RE
.RS 4
QUEUE_DEFAULT="none"
.RE
.RS 4
NFQUEUE_DEFAULT="None"
.RE
If you set the value of either option to "None" then no default action will be used and the default action or macro must be specified in
\m[blue]\fBshorewall6\-policy\fR\m[]\&\s-2\u[1]\d\s+2(5)\&.
.sp
You can pass
\fIparameters\fR
to the specified action or macro (e\&.g\&.,
\fImyaction(audit,DROP)\fR)\&.
.sp
Beginning with Shorewall 4\&.5\&.10, the action name can be followed optionally by a colon and a log
\fIlevel\fR\&. The level will be applied to each rule in the action or macro body that does not already have a log level\&.
.RE
.PP
\fBACCOUNTING=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Added in Shorewall 4\&.4\&.7\&. If set to Yes, Shorewall6 accounting is enabled (see
\m[blue]\fBshorewall6\-accounting\fR\m[]\&\s-2\u[2]\d\s+2(5))\&. If not specified or set to the empty value, ACCOUNTING=Yes is assumed\&.
.RE
.PP
\fBACCOUNTING_TABLE=\fR[\fBfilter\fR|\fBmangle\fR]
.RS 4
Added in Shorewall 4\&.4\&.20\&. This setting determines which Netfilter table the accounting rules are added in\&. By default, ACCOUNTING_TABLE=filter is assumed\&. See also
\m[blue]\fBshorewall\-accounting\fR\m[]\&\s-2\u[3]\d\s+2(5)\&.
.RE
.PP
\fBADMINISABSENTMINDED=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
The value of this variable affects Shorewall6\*(Aqs stopped state\&. When ADMINISABSENTMINDED=No, only traffic to/from those addresses listed in
\m[blue]\fBshorewall6\-routestopped\fR\m[]\&\s-2\u[4]\d\s+2(5) is accepted when Shorewall6 is stopped\&. When ADMINISABSENTMINDED=Yes, in addition to traffic to/from addresses in
\m[blue]\fBshorewall6\-routestopped\fR\m[]\&\s-2\u[4]\d\s+2(5), connections that were active when Shorewall6 stopped continue to work and all new connections from the firewall system itself are allowed\&. If this variable is not set or is given the empty value then ADMINISABSENTMINDED=No is assumed\&.
.RE
.PP
\fBIGNOREUNKNOWNVARIABLES=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Added in Shorewall 4\&.5\&.11\&. Normally, if an unknown shell variable is encountered in a configuration file (except in ?IF and ?ELSIF directives), the compiler raises a fatal error\&. If IGNOREUNKNOWNVARIABLES is set to
\fBYes\fR, then such variables simply expand to an empty string\&. Default is
\fBNo\fR\&.
.RE
.PP
\fBAUTOCOMMENT=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Formerly named AUTO_COMMENT\&. If set, if there is not a current comment when a macro is invoked, the behavior is as if the first line of the macro file was "COMMENT <macro name>"\&. The AUTO_COMMENT option has a default value of \*(AqYes\*(Aq\&.
.RE
.PP
\fBAUTOHELPERS=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Added in Shorewall 4\&.5\&.7\&. When set to
\fBYes\fR
(the default), the generated ruleset will automatically associate helpers with applications that require them (FTP, IRC, etc\&.)\&. When configuring your firewall on systems running kernel 3\&.5 or later, it is recommended that you:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Set AUTOHELPERS=No\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Either:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Modify
\m[blue]\fBshorewall6\-conntrack\fR\m[]\&\s-2\u[5]\d\s+2
(5) to only apply helpers where they are required; or
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Specify the appropriate helper in the HELPER column in
\m[blue]\fBshorewall6\-rules\fR\m[]\&\s-2\u[6]\d\s+2
(5)\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
The macros for those applications requiring a helper automatically specify the appropriate HELPER where required\&.
.sp .5v
.RE
.RE
.RE
.RE
.PP
\fBAUTOMAKE=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
If set, the behavior of the
\fBstart\fR
and
\fBrestart\fR
commands is change; if no files in
/etc/shorewall
have been changed since the last successful
\fBstart\fR
or
\fBrestart\fR
command, then the compilation step is skipped and the compiled script that executed the last
\fBstart\fR
or
\fBrestart\fR
command is used\&. The default is AUTOMAKE=No\&.
.sp
The setting of the AUTOMAKE option is ignored if the
\fBstart\fR
or
\fBrestart\fR
command includes a directory name (e\&.g\&.,\fB shorewall6 restart /etc/shorewall\&.new\fR)\&.
.RE
.PP
\fBBLACKLIST=\fR[{\fBALL\fR|\fB\fIstate\fR\fR\fB[,\&.\&.\&.]\fR}]
.RS 4
where state is one of NEW, ESTABLISHED, RELATED, INVALID,or UNTRACKED\&.
.sp
Added in Shorewall 4\&.5\&.13 to replace the BLACKLISTNEWONLY option below\&. Specifies the connection tracking states that are to be subject to blacklist screening\&. If neither BLACKLIST nor BLACKLISTNEWONLY are specified then the states subject to blacklisting are NEW,ESTABLISHED,INVALID,UNTRACKED\&.
.sp
Note: The ESTABLISHED state may not be specified if FASTACCEPT is specified\&.
.RE
.PP
\fBBLACKLIST_DISPOSITION=\fR[\fBDROP\fR|A_DROP|\fBREJECT|A_REJECT\fR]
.RS 4
This parameter determines the disposition of packets from blacklisted hosts\&. It may have the value DROP if the packets are to be dropped or REJECT if the packets are to be replied with an ICMP port unreachable reply or a TCP RST (tcp only)\&. If you do not assign a value or if you assign an empty value then DROP is assumed\&. The setting determines the disposition of packets sent to the
\fBblacklog\fR
target of
\m[blue]\fBshorewall6\-blrules\fR\m[]\&\s-2\u[7]\d\s+2(5)\&.
.RE
.PP
\fBBLACKLIST_LOG_LEVEL=\fR[\fIlog\-level\fR]
.RS 4
Formerly named BLACKLIST_LOGLEVEL\&. This parameter determines if packets from blacklisted hosts are logged and it determines the syslog level that they are to be logged at\&. Its value is a syslog level (Example: BLACKLIST_LOG_LEVEL=debug)\&. If you do not assign a value or if you assign an empty value then packets from blacklisted hosts are not logged\&. The setting determines the log level of packets sent to the
\fBblacklog\fR
target of
\m[blue]\fBshorewall6\-blrules\fR\m[]\&\s-2\u[7]\d\s+2(5)\&.
.RE
.PP
\fBBLACKLISTNEWONLY=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Deprecated in Shorewall 4\&.5\&.13 in favor of BLACKLIST above\&.
.sp
When set to
\fBYes\fR
or
\fByes\fR, blacklists are only consulted for new connections, for packets in the INVALID connection state (such as a TCP SYN,ACK when there has been no corresponding SYN), and for packets that are UNTRACKED due to entries in
\m[blue]\fBshorewall6\-conntrack\fR\m[]\&\s-2\u[8]\d\s+2(5)\&. This includes entries in the
\m[blue]\fBshorewall6\-blrules\fR\m[]\&\s-2\u[7]\d\s+2
(5) file and in the BLACKLIST section of
\m[blue]\fBshorewall6\-rules\fR\m[]\&\s-2\u[6]\d\s+2
(5)\&.
.sp
When set to
\fBNo\fR
or
\fBno\fR, blacklists are consulted for every packet (will slow down your firewall noticeably if you have large blacklists)\&. If the BLACKLISTNEWONLY option is not set or is set to the empty value then BLACKLISTNEWONLY=No is assumed\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
BLACKLISTNEWONLY=No is incompatible with FASTACCEPT=Yes\&.
.sp .5v
.RE
.RE
.PP
\fBCHAIN_SCRIPTS=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Added in Shorewall 4\&.5\&.16\&. Prior to the availability of BEGIN PERL\&.\&.\&.\&.END PERL in configuration files, the only way to execute a chain\-specific script was to create a script file with the same name as the chain and place it in a directory on the CONFIG_PATH\&. That facility has the drawback that the compiler will attempt to run a non\-script file just because it has the same name as a chain\&. To disable this facility, set CHAIN_SCRIPTS=No\&. If not specified or specified as the empty value, CHAIN_SCRIPTS=Yes is assumed\&.
.RE
.PP
\fBCLAMPMSS=[\fR\fBYes\fR|\fBNo\fR|\fIvalue\fR]
.RS 4
This parameter enables the TCP Clamp MSS to PMTU feature of Netfilter and is usually required when your internet connection is through PPPoE or PPTP\&. If set to
\fBYes\fR
or
\fByes\fR, the feature is enabled\&. If left blank or set to
\fBNo\fR
or
\fBno\fR, the feature is not enabled\&.
.sp
\fBImportant\fR: This option requires CONFIG_IP_NF_TARGET_TCPMSS in your kernel\&.
.sp
You may also set CLAMPMSS to a numeric
\fIvalue\fR
(e\&.g\&., CLAMPMSS=1400)\&. This will set the MSS field in TCP SYN packets going through the firewall to the
\fIvalue\fR
that you specify\&.
.RE
.PP
\fBCLEAR_TC=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
If this option is set to
\fBNo\fR
then Shorewall6 won\*(Aqt clear the current traffic control rules during [re]start\&. This setting is intended for use by people that prefer to configure traffic shaping when the network interfaces come up rather than when the firewall is started\&. If that is what you want to do, set TC_ENABLED=Yes and CLEAR_TC=No and do not supply an /etc/shorewall6/tcstart file\&. That way, your traffic shaping rules can still use the \(lqfwmark\(rq classifier based on packet marking defined in
\m[blue]\fBshorewall6\-tcrules\fR\m[]\&\s-2\u[9]\d\s+2(5)\&. If not specified, CLEAR_TC=No is assumed\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBWarning\fR
.ps -1
.br
If you also run Shorewall and if you have TC_ENABLED=Internal in your
\m[blue]\fBshorewall\-conf\fR\m[]\&\s-2\u[10]\d\s+2(5), then you will want CLEAR_TC=No in this file\&.
.sp .5v
.RE
.RE
.PP
\fBCOMPLETE=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Added in Shorewall6 4\&.4\&.12\&. When you set this option to Yes, you are asserting that the configuration is complete so that your set of zones encompasses any hosts that can send or receive traffic to/from/through the firewall\&. This causes Shorewall6 to omit the rules that catch packets in which the source or destination IP address is outside of any of your zones\&. Default is No\&. It is recommended that this option only be set to Yes if:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
You have defined an interface whose effective physical setting is \*(Aq+\*(Aq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
That interface is assigned to a zone\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
You have no CONTINUE policies or rules\&.
.RE
.RE
.PP
\fBCONFIG_PATH\fR=[\fIdirectory\fR[:\fIdirectory\fR]\&.\&.\&.]
.RS 4
Specifies where configuration files other than shorewall6\&.conf may be found\&. CONFIG_PATH is specifies as a list of directory names separated by colons (":")\&. When looking for a configuration file other than shorewall6\&.conf:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If the command is "try" or a "<configuration directory>" was specified in the command (e\&.g\&.,
\fBshorewall6 check \&./gateway\fR) then the directory given in the command is searched first\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Next, each directory in the CONFIG_PATH setting is searched in sequence\&.
.RE
.sp
If CONFIG_PATH is not given or if it is set to the empty value then the contents of /usr/share/shorewall6/configpath are used\&. As released from shorewall\&.net, that file sets the CONFIG_PATH to /etc/shorewall6:/usr/share/shorewall6:/usr/share/shorewall but your particular distribution may set it differently\&. See the output of shorewall6 show config for the default on your system\&.
.RE
.PP
\fBDEFER_DNS_RESOLUTION=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Added in Shorewall 4\&.5\&.12\&. When set to \*(AqYes\*(Aq (the default), DNS names are validated in the compiler and then passed on to the generated script where they are resolved by ip6tables\-restore\&. This is an advantage if you use AUTOMAKE=Yes and the IP address associated with the DNS name is subject to change\&. When DEFER_DNS_RESOLUTION=No, DNS names are converted into IP addresses by the compiler\&. This has the advantage that when AUTOMAKE=Yes the
\fBstart\fR
and
\fBrestart\fR
commands will succeed even if no DNS server is reachable (assuming that the configuration hasn\*(Aqt changed since the compiled script was last generated)\&.
.RE
.PP
\fBDELETE_THEN_ADD=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
If set to Yes (the default value), entries in the /etc/shorewall6/route_stopped files cause an \*(Aqip rule del\*(Aq command to be generated in addition to an \*(Aqip rule add\*(Aq command\&. Setting this option to No, causes the \*(Aqip rule del\*(Aq command to be omitted\&.
.RE
.PP
\fBDONT_LOAD=\fR[\fImodule\fR[,\fImodule\fR]\&.\&.\&.]
.RS 4
Causes Shorewall6 to not load the listed kernel modules\&.
.RE
.PP
\fBDYNAMIC_BLACKLIST=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Added in Shorewall 4\&.4\&.7\&. When set to
\fBNo\fR
or
\fBno\fR, dynamic blacklisting using the
\fBshorewall6 drop\fR,
\fBshorewall6 reject\fR,
\fBshorewall6 logdrop\fR
and
\fBshorewall6 logreject\fR
is disabled\&. Default is
\fBYes\fR\&.
.RE
.PP
\fBEXPAND_POLICIES=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Normally, when the SOURCE or DEST columns in shorewall\-policy(5) contains \*(Aqall\*(Aq, a single policy chain is created and the policy is enforced in that chain\&. For example, if the policy entry is
.sp
.if n \{\
.RS 4
.\}
.nf
#SOURCE DEST POLICY LOG
#                   LEVEL
net     all  DROP   info
.fi
.if n \{\
.RE
.\}
.sp
then the chain name is \*(Aqnet2all\*(Aq which is also the chain named in Shorewall log messages generated as a result of the policy\&. If EXPAND_POLICIES=Yes, then Shorewall will create a separate chain for each pair of zones covered by the policy\&. This makes the resulting log messages easier to interpret since the chain in the messages will have a name of the form \*(Aqa2b\*(Aq where \*(Aqa\*(Aq is the SOURCE zone and \*(Aqb\*(Aq is the DEST zone\&.
.RE
.PP
\fBEXPORTMODULES=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Added in Shorewall 4\&.4\&.17\&. When set to Yes when compiling for use by Shorewall6 Lite (\fBshorewall6 load\fR,
\fBshorewall6 reload \fRor
\fBshorewall6 export\fR
commands), the compiler will copy the modules or helpers file from the administrative system into the script\&. When set to No or not specified, the compiler will not copy the modules or helpers file from
/usr/share/shorewall6
but will copy the found in another location on the CONFIG_PATH\&.
.sp
When compiling for direct use by Shorewall6, causes the contents of the local module or helpers file to be copied into the compiled script\&. When set to No or not set, the compiled script reads the file itself\&.
.RE
.PP
\fBEXPORTPARAMS=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Deprecated beginning with Shorewall 4\&.4\&.17\&.
.sp
Beginning with Shorewall 4\&.4\&.17, the variables set in the \*(Aqparams\*(Aq file at compile time are available at run time with EXPORTPARAMS=No\&. As a consequence, beginning with that version the recommended setting is EXPORTPARAMS=No\&.
.sp
It is quite difficult to code a \*(Aqparams\*(Aq file that assigns other than constant values such that it works correctly with Shorewall6 Lite\&. The EXPORTPARAMS option works around this problem\&. When EXPORTPARAMS=No, the \*(Aqparams\*(Aq file is not copied to the compiler output\&.
.sp
With EXPORTPARAMS=No, if you need to set environmental variables on the firewall system for use by your extension scripts, then do so in the init extension script\&.
.sp
The default is EXPORTPARAMS=Yes which is the recommended setting unless you are running Shorewall6 Lite\&.
.RE
.PP
\fBFASTACCEPT=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Normally, Shorewall6 defers accepting ESTABLISHED/RELATED packets until these packets reach the chain in which the original connection was accepted\&. So for packets going from the \*(Aqloc\*(Aq zone to the \*(Aqnet\*(Aq zone, ESTABLISHED/RELATED packets are ACCEPTED in the \*(Aqloc2net\*(Aq chain\&.
.sp
If you set FASTACCEPT=Yes, then ESTABLISHED/RELATED packets are accepted early in the INPUT, FORWARD and OUTPUT chains\&. If you set FASTACCEPT=Yes then you may not include rules in the ESTABLISHED or RELATED sections of
\m[blue]\fBshorewall6\-rules\fR\m[]\&\s-2\u[6]\d\s+2(5)\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
FASTACCEPT=Yes is incompatible with BLACKLISTNEWONLY=No\&.
.sp .5v
.RE
.RE
.PP
\fBFORWARD_CLEAR_MARK=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Added in Shorewall 4\&.4\&.11 Beta 3\&. Traditionally, Shorewall has cleared the packet mark in the first rule in the mangle FORWARD chain\&. This behavior is maintained with the default setting of this option (FORWARD_CLEAR_MARK=Yes)\&. If FORWARD_CLEAR_MARK is set to \*(AqNo\*(Aq, packet marks set in the mangle PREROUTING chain are retained in the FORWARD chains\&.
.RE
.PP
\fBGEOIPDIR\fR=[\fIpathname\fR]
.RS 4
Added in Shorewall 4\&.5\&.4\&. Specifies the pathname of the directory containing the
GeoIP Match
database\&. See
\m[blue]\fBhttp://www\&.shorewall\&.net/ISO\-3661\&.html\fR\m[]\&. If not specified, the default value is
/usr/share/xt_geoip/LE
which is the default location of the little\-endian database\&.
.RE
.PP
\fBHELPERS\fR=[\fIhelper\fR[,\fIhelper\fR\&.\&.\&.]]
.RS 4
Added in Shorewall 4\&.5\&.7\&. This option lists the Netfilter application helps that are to be enabled\&. If not specified, the default is to enable all helpers\&.
.sp
Possible values for
\fIhelper\fR
are:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBamanda\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBftp\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBh323\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBirc\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBnetbios\-ns\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBnone\fR
\- This special value was added in Shorewall 4\&.5\&.16 and indicates that no helpers are to be enabled\&. It also prevents the compiler for probing for helper support; such probing generates messages on the system log of the form "xt_CT: No such helper XXX" where XXX is the helper name\&. When used,
\fBnone\fR
must be the only helper specified\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBpptp\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBsane\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBsip\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBsnmp\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBtftp\fR
.RE
.sp
When HELPERS is specified on a system running Kernel 3\&.5\&.0 or later, automatic association of helpers to connections is disabled\&.
.RE
.PP
\fBHIGH_ROUTE_MARKS=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Deprecated in Shorewall 4\&.4\&.26 in favor of PROVIDER_OFFSET\&.
.sp
You may set HIGH_ROUTE_MARKS=Yes in to effectively divide the packet mark and connection mark into two mark fields\&.
.sp
The width of the fields are determined by the setting of the WIDE_TC_MARKS option\&.
.sp
When WIDE_TC_MARKS=No (the default):
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
The MARK field in the providers file must have a value that is less than 65536 and that is a multiple of 256 (using hex representation, the values are 0x0100\-0xFF00 with the low\-order 8 bits being zero)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
You may only set those mark values in the PREROUTING chain\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Marks used for traffic shaping must still be in the range of 1\-255 and may still not be set in the PREROUTING chain\&.
.RE
.sp
When WIDE_TC_MARKS=Yes:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
The MARK field in the providers file must have a value that is a multiple of 65536 (using hex representation, the values are 0x010000\-0xFF0000 with the low\-order 16 bits being zero)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
You may only set those mark values in the PREROUTING chain\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Marks used for traffic shaping must be in the range of 1\-16383 and may still not be set in the PREROUTING chain\&.
.RE
.sp
Regardless of the setting of WIDE_TC_MARKS, when you SAVE or RESTORE in tcrules, only the TC mark value is saved or restored\&. Shorewall handles saving and restoring the routing (provider) marks\&.
.RE
.PP
\fBIMPLICIT_CONTINUE=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
When this option is set to
\fBYes\fR, it causes subzones to be treated differently with respect to policies\&.
.sp
Subzones are defined by following their name with ":" and a list of parent zones (in
\m[blue]\fBshorewall6\-zones\fR\m[]\&\s-2\u[11]\d\s+2(5))\&. Normally, you want to have a set of special rules for the subzone and if a connection doesn\*(Aqt match any of those subzone\-specific rules then you want the parent zone rules and policies to be applied; see
\m[blue]\fBshorewall6\-nesting\fR\m[]\&\s-2\u[12]\d\s+2(5)\&. With IMPLICIT_CONTINUE=Yes, that happens automatically\&.
.sp
If IMPLICIT_CONTINUE=No or if IMPLICIT_CONTINUE is not set, then subzones are not subject to this special treatment\&. With IMPLICIT_CONTINUE=Yes, an implicit CONTINUE policy may be overridden by including an explicit policy (one that does not specify "all" in either the SOURCE or the DEST columns)\&.
.RE
.PP
\fBINVALID_DISPOSITION=[A_DROP|A_REJECT|DROP|REJECT|CONTINUE]\fR
.RS 4
Added in Shorewall 4\&.5\&.13\&. Shorewall has traditionally passed INVALID packets through the NEW section of
\m[blue]\fBshorewall\-rules\fR\m[]\&\s-2\u[6]\d\s+2
(5)\&. When a packet in INVALID state fails to match any rule in the INVALID section, the packet is disposed of based on this setting\&. The default value is CONTINUE for compatibility with earlier versions\&.
.RE
.PP
\fBINVALID_LOG_LEVEL=\fR\fIlog\-level\fR
.RS 4
Added in Shorewall 4\&.5\&.13\&. Packets in the INVALID state that do not match any rule in the INVALID section of
\m[blue]\fBshorewall\-rules\fR\m[]\&\s-2\u[13]\d\s+2
(5) are logged at this level\&. The default value is empty which means no logging is performed\&.
.RE
.PP
\fBIP\fR=[\fIpathname\fR]
.RS 4
If specified, gives the pathname of the \*(Aqip\*(Aq executable\&. If not specified, \*(Aqip\*(Aq is assumed and the utility will be located using the current PATH setting\&.
.RE
.PP
\fBIP_FORWARDING=\fR[\fBOn\fR|\fBOff\fR|\fBKeep\fR]
.RS 4
This rather useless parameter determines whether Shorewall6 enables or disables IPV6 Packet Forwarding on all interfaces (/proc/sys/net/ipv6/config/all/forwarding)\&. Possible values are:
.PP
\fBOn\fR or \fBon\fR
.RS 4
packet forwarding will be enabled\&.
.RE
.PP
\fBOff\fR or \fBoff\fR
.RS 4
packet forwarding will be disabled\&.
.RE
.PP
\fBKeep\fR or \fBkeep\fR
.RS 4
Shorewall6 will neither enable nor disable packet forwarding
.RE
.sp
If this variable is not set or is given an empty value (IP_FORWARD="") then IP_FORWARD=On is assumed\&.
.RE
.PP
\fBIP6TABLES=\fR[\fIpathname\fR]
.RS 4
This parameter names the ip6tables executable to be used by Shorewall6\&. If not specified or if specified as a null value, then the ip6tables executable located using the PATH option is used\&.
.sp
Regardless of how the ip6tables utility is located (specified via IP6TABLES= or located via PATH), Shorewall6 uses the ip6tables\-restore and ip6tables\-save utilities from that same directory\&.
.RE
.PP
\fBIPSET\fR=[\fIpathname\fR]
.RS 4
If specified, gives the pathname of the \*(Aqipset\*(Aq executable\&. If not specified, \*(Aqipset\*(Aq is assumed and the utility will be located using the current PATH setting\&.
.RE
.PP
\fBIPSET_WARNINGS=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Added in Shorewall 4\&.5\&.2\&. Default is Yes\&. When set, causes the rules compiler to issue a warning when:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
The compiler is being run by root and an ipset specified in the configuration does not exists\&. Only one warning is issued for each missing ipset\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
When [src] is specified in a destination column and when [dst] is specified in a source column\&.
.RE
.RE
.PP
\fBKEEP_RT_TABLES=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
When set to
\fBYes\fR, this option prevents scripts generated by Shorewall6 from altering the /etc/iproute2/rt_tables database when there are entries in
/etc/shorewall6/providers\&. If you set this option to
\fBYes\fR
while Shorewall6 (Shorewall6\-lite) is running, you should remove the file
/var/lib/shorewall6/rt_tables
(/var/lib/shorewall6\-lite/rt_tables) before your next
\fBstop\fR,
\fBrefresh\fR,
\fBrestore\fR
on
\fBrestart\fR
command\&.
.sp
The default is KEEP_RT_TABLES=No\&.
.RE
.PP
\fBLEGACY_FASTSTART=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Added in Shorewall6 4\&.4\&.20\&. If not specified, the default is Yes which preserves the legacy behavior of
\fBstart \-f\fR
(the modification times of the files in
/etc/shorewall6
are compare with that of
/var/lib/shorewall6/restore)\&. If set to No, then the times are compared with that of /var/lib/shorewall6/firewall, which is consistent with the way that
\fBrestart \-f\fR
works\&.
.RE
.PP
\fBLOAD_HELPERS_ONLY=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Added in Shorewall 4\&.4\&.7\&. When set to Yes, restricts the set of modules loaded by shorewall to those listed in /var/lib/shorewall6/helpers and those that are actually used\&. When not set, or set to the empty value, LOAD_HELPERS_ONLY=No is assumed\&.
.RE
.PP
\fBLOCKFILE\fR=[\fIpathname\fR]
.RS 4
Specifies the name of the Shorewall6 lock file, used to prevent simultaneous state\-changing commands\&. If not specified, ${VARDIR}/shorewall6/lock is assumed (${VARDIR} is normally /var/lib but can be changed when Shorewall\-core is installed \-\- see the output of
\fBshorewall6 show vardir\fR)\&.
.RE
.PP
\fBLOG_VERBOSITY=\fR[\fInumber\fR]
.RS 4
This option controls the amount of information logged to the file specified in the STARTUP_LOG option\&.
.sp
Values are:
.RS 4
\-1 \- Logging is disabled
.RE
.RS 4
0 \- Silent\&. Only error messages are logged\&.
.RE
.RS 4
1 \- Major progress messages logged\&.
.RE
.RS 4
2 \- All progress messages logged
.RE
If not specified, then \-1 is assumed\&.
.RE
.PP
\fBLOGALLNEW=\fR[\fIlog\-level\fR]
.RS 4
This option is intended for use as a debugging aid\&. When set to a log level, this option causes Shorewall6 to generate a logging rule as the first rule in each builtin chain\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
The table name is used as the chain name in the log prefix\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
The chain name is used as the target in the log prefix\&.
.RE
.sp

For example, using the default LOGFORMAT, the log prefix for logging from the nat table\*(Aqs PREROUTING chain is:
.sp
.if n \{\
.RS 4
.\}
.nf
    Shorewall:nat:PREROUTING
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBImportant\fR
.ps -1
.br
To help insure that all packets in the NEW state are logged, rate limiting (LOGBURST and LOGRATE) should be disabled when using LOGALLNEW\&. Use LOGALLNEW at your own risk; it may cause high CPU and disk utilization and you may not be able to control your firewall after you enable this option\&.
.sp .5v
.RE
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBCaution\fR
.ps -1
.br
Do not use this option if the resulting log messages will be sent to another system\&.
.sp .5v
.RE
.RE
.PP
\fBLOGFILE=\fR[\fIpathname\fR]
.RS 4
This parameter tells the /sbin/shorewall6 program where to look for Shorewall6 messages when processing the
\fBdump\fR,
\fBlogwatch\fR,
\fBshow log\fR, and
\fBhits\fR
commands\&. If not assigned or if assigned an empty value, /var/log/messages is assumed\&.
.RE
.PP
\fBLOGFORMAT=\fR[\fB"\fR\fIformattemplate\fR\fB"\fR]
.RS 4
The value of this variable generate the \-\-log\-prefix setting for Shorewall6 logging rules\&. It contains a \(lqprintf\(rq formatting template which accepts three arguments (the chain name, logging rule number (optional) and the disposition)\&. To use LOGFORMAT with fireparse, set it as:
.sp
.if n \{\
.RS 4
.\}
.nf
    LOGFORMAT="fp=%s:%d a=%s "
.fi
.if n \{\
.RE
.\}
.sp
If the LOGFORMAT value contains the substring \(lq%d\(rq then the logging rule number is calculated and formatted in that position; if that substring is not included then the rule number is not included\&. If not supplied or supplied as empty (LOGFORMAT="") then \(lqShorewall6:%s:%s:\(rq is assumed\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
The setting of LOGFORMAT has an effect of the permitted length of zone names\&. See
\m[blue]\fBshorewall6\-zones\fR\m[]\&\s-2\u[11]\d\s+2
(5)\&.
.sp .5v
.RE
.RE
.PP
\fBLOGLIMIT=[\fR[{\fIs\fR|\fBd\fR}:]\fIrate\fR\fB/\fR{\fBsec\fR|\fBmin\fR|\fBhour\fR|\fBday\fR}[:\fIburst\fR]]
.RS 4
Added in Shorewall 4\&.4\&.12\&. Limits the logging rate, either overall, or by source or destination IP address\&.
.sp
If the value starts with \*(Aqs:\*(Aq then logging is limited per source IP\&. If the value starts with \*(Aqd:\*(Aq, then logging is limited per destination IP\&. Otherwise, the overall logging rate is limited\&.
.sp
If
\fIburst\fR
is not specified, then a value of 5 is assumed\&.
.RE
.PP
\fBLOGBURST=\fR[\fIburst\fR]
.RS 4
Deprecated in Shorewall 4\&.4\&.12\&.
.RE
.PP
\fBLOGRATE=\fR[\fIrate\fR/{\fBminute\fR|\fBsecond\fR}]
.RS 4
As of Shorewall 4\&.4\&.12, these parameters are Deprecated\&.
.sp
These parameters set the match rate and initial burst size for logged packets\&. Please see ip6tables(8) for a description of the behavior of these parameters (the ip6tables option \-\-limit is set by LOGRATE and \-\-limit\-burst is set by LOGBURST)\&. If both parameters are set empty, no rate\-limiting will occur\&. If you supply one of these, then you should also supply the other\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
    LOGRATE=10/minute
    LOGBURST=5
.fi
.if n \{\
.RE
.\}
.sp
For each logging rule, the first time the rule is reached, the packet will be logged; in fact, since the burst is 5, the first five packets will be logged\&. After this, it will be 6 seconds (1 minute divided by the rate of 10) before a message will be logged from the rule, regardless of how many packets reach it\&. Also, every 6 seconds, one of the bursts will be regained; if no packets hit the rule for 30 seconds, the burst will be fully recharged; back where we started\&.
.RE
.PP
\fBLOGTAGONLY=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Using the default LOGFORMAT, chain names may not exceed 11 characters or truncation of the log prefix may occur\&. Longer chain names may be used with log tags if you set LOGTAGONLY=Yes\&. With LOGTAGONLY=Yes, if a log tag is specified then the tag is included in the log prefix in place of the chain name\&.
.sp
Beginning with Shorewall 4\&.5\&.12, when LOGTAGONLY=Yes, you have more control over the generated log prefix\&. Beginning with that release, the tag is interpreted as a
\fIchain name\fR
and a
\fIdisposition\fR
separated by a comma\&. So this rule:
.sp
.if n \{\
.RS 4
.\}
.nf
#ACTION                                SOURCE         DEST
LOG:info:foo,bar                 net                   fw
.fi
.if n \{\
.RE
.\}
.sp
would generate the following log prefix when using the default LOGFORMAT setting:
.RS 4
Shorewall:foo:bar:
.RE
Similarly,
.sp
.if n \{\
.RS 4
.\}
.nf
#ACTION                               SOURCE            DEST
LOG:info:,bar                        net                    fw
.fi
.if n \{\
.RE
.\}
.sp
would generate
.RS 4
Shorewall:net2fw:bar:
.RE
.RE
.PP
\fBMACLIST_DISPOSITION=\fR[\fBACCEPT\fR|\fBDROP\fR|\fBREJECT\fR|A_DROP|A_REJECT]
.RS 4
Determines the disposition of connections requests that fail MAC Verification and must have the value ACCEPT (accept the connection request anyway), REJECT (reject the connection request) or DROP (ignore the connection request)\&. If not set or if set to the empty value (e\&.g\&., MACLIST_DISPOSITION="") then MACLIST_DISPOSITION=REJECT is assumed\&.
.sp
A_DROP and A_REJECT are audited versions of DROP and REJECT respectively and were added in Shorewall 4\&.4\&.20\&. They require AUDIT_TARGET in the kernel and ip6tables\&.
.RE
.PP
\fBMACLIST_LOG_LEVEL=\fR[\fIlog\-level\fR]
.RS 4
Determines the syslog level for logging connection requests that fail MAC Verification\&. The value must be a valid syslogd log level\&. If you don\*(Aqt want to log these connection requests, set to the empty value (e\&.g\&., MACLIST_LOG_LEVEL="")\&.
.RE
.PP
\fBMACLIST_TABLE=\fR[\fBfilter\fR|\fBmangle\fR]
.RS 4
Normally, MAC verification occurs in the filter table (INPUT and FORWARD) chains\&. When forwarding a packet from an interface with MAC verification to a bridge interface, that doesn\*(Aqt work\&.
.sp
This problem can be worked around by setting MACLIST_TABLE=mangle which will cause Mac verification to occur out of the PREROUTING chain\&. Because REJECT isn\*(Aqt available in that environment, you may not specify MACLIST_DISPOSITION=REJECT with MACLIST_TABLE=mangle\&.
.RE
.PP
\fBMACLIST_TTL=[\fR\fInumber\fR]
.RS 4
The performance of configurations with a large numbers of entries in
\m[blue]\fBshorewall\-maclist\fR\m[]\&\s-2\u[14]\d\s+2(5) can be improved by setting the MACLIST_TTL variable in
\m[blue]\fBshorewall\&.conf\fR\m[]\&\s-2\u[15]\d\s+2(5)\&.
.sp
If your iptables and kernel support the "Recent Match" (see the output of "shorewall check" near the top), you can cache the results of a \*(Aqmaclist\*(Aq file lookup and thus reduce the overhead associated with MAC Verification\&.
.sp
When a new connection arrives from a \*(Aqmaclist\*(Aq interface, the packet passes through then list of entries for that interface in
\m[blue]\fBshorewall\-maclist\fR\m[]\&\s-2\u[14]\d\s+2(5)\&. If there is a match then the source IP address is added to the \*(AqRecent\*(Aq set for that interface\&. Subsequent connection attempts from that IP address occurring within $MACLIST_TTL seconds will be accepted without having to scan all of the entries\&. After $MACLIST_TTL from the first accepted connection request from an IP address, the next connection request from that IP address will be checked against the entire list\&.
.sp
If MACLIST_TTL is not specified or is specified as empty (e\&.g, MACLIST_TTL="" or is specified as zero then \*(Aqmaclist\*(Aq lookups will not be cached)\&.
.RE
.PP
\fBMANGLE_ENABLED=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Determines whether Shorewall will generate rules in the Netfilter mangle table\&. Setting MANGLE_ENABLED=No disables all Shorewall features that require the mangle table\&. The default is MANGLE_ENABLED=Yes\&.
.RE
.PP
\fBMARK_IN_FORWARD_CHAIN=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
If your kernel has a FORWARD chain in the mangle table, you may set MARK_IN_FORWARD_CHAIN=Yes to cause the marking specified in the tcrules file to occur in that chain rather than in the PREROUTING chain\&. This permits you to mark inbound traffic based on its destination address when DNAT is in use\&. To determine if your kernel has a FORWARD chain in the mangle table, use the
\fB/sbin/shorewall6 show mangle\fR
command; if a FORWARD chain is displayed then your kernel will support this option\&. If this option is not specified or if it is given the empty value (e\&.g\&., MARK_IN_FORWARD_CHAIN="") then MARK_IN_FORWARD_CHAIN=No is assumed\&.
.RE
.PP
\fBMASK_BITS\fR=[\fInumber\fR]
.RS 4
Added in Shorewall 4\&.4\&.26\&. Number of bits on the right of the 32\-bit packet mark to be masked when clearing the traffic shaping mark\&. Must be >= TC_BITS and <= PROVIDER_OFFSET (if PROVIDER_OFFSET > 0)\&. Default value and the default values of the other mark layout options is determined as follows:
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&1.\ \&Default Packet Mark Layout
.TS
tab(:);
l l
l l
l l
l l.
T{
WIDE_TC_MARKS=No, HIGH_ROUTE_MARKS=No
T}:T{
TC_BITS=8, PROVIDER_BITS=8, PROVIDER_OFFSET=0,
                  MASK_BITS=8
T}
T{
WIDE_TC_MARKS=No, HIGH_ROUTE_MARKS=Yes
T}:T{
TC_BITS=8, PROVIDER_BITS=8, PROVIDER_OFFSET=8,
                  MASK_BITS=8
T}
T{
WIDE_TC_MARKS=Yes, HIGH_ROUTE_MARKS=No
T}:T{
TC_BITS=14, PROVIDER_BITS=8, PROVIDER_OFFSET=0,
                  MASK_BITS=16
T}
T{
WIDE_TC_MARKS=Yes, HIGH_ROUTE_MARKS=Yes
T}:T{
TC_BITS=14, PROVIDER_BITS=8, PROVIDER_OFFSET=16,
                  MASK_BITS=16
T}
.TE
.sp 1
.RE
.PP
\fBMODULE_SUFFIX=\fR[\fB"\fR\fIextension\fR \&.\&.\&.\fB"\fR]
.RS 4
The value of this option determines the possible file extensions of kernel modules\&. The default value is "ko ko\&.gz o o\&.gz gz"\&.
.RE
.PP
\fBMODULESDIR=\fR[\fIpathname\fR[\fB:\fR\fIpathname\fR]\&.\&.\&.]
.RS 4
This parameter specifies the directory/directories where your kernel netfilter modules may be found\&. If you leave the variable empty, Shorewall6 will supply "/lib/modules/`uname \-r`/kernel/net/ipv4/netfilter:/lib/modules/`uname \-r`/kernel/net/ipv4/netfilter"\&.
.RE
.PP
\fBMUTEX_TIMEOUT=\fR[\fIseconds\fR]
.RS 4
The value of this variable determines the number of seconds that programs will wait for exclusive access to the Shorewall6 lock file\&. After the number of seconds corresponding to the value of this variable, programs will assume that the last program to hold the lock died without releasing the lock\&.
.sp
If not set or set to the empty value, a value of 60 (60 seconds) is assumed\&.
.sp
An appropriate value for this parameter would be twice the length of time that it takes your firewall system to process a
\fBshorewall6 restart\fR
command\&.
.RE
.PP
\fBNFACCT=\fR[\fIpathname\fR]
.RS 4
Added in Shorewall 4\&.5\&.7\&. Specifies the pathname of the nfacct utility\&. If not specified, Shorewall will use the PATH setting to find the program\&.
.RE
.PP
\fBOPTIMIZE=\fR[\fIvalue\fR]
.RS 4
The specified
\fIvalue\fR
enables certain optimizations\&. Each optimization category is associated with a power of two\&. To enable multiple optimization categories, simply add their corresponding numbers together\&.
.sp
Beginning with Shorewall 4\&.5\&.20, you may specify OPTIMIZE=All to enable all optimization categories, and you may also specify OPTIMIZE=None to disable optimization\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Optimization category 1 \- Traditionally, Shorewall has created rules for
\m[blue]\fBthe complete matrix of host groups defined by the zones, interfaces and hosts files\fR\m[]\&\s-2\u[16]\d\s+2\&. Any traffic that didn\*(Aqt correspond to an element of that matrix was rejected in one of the built\-in chains\&. When the matrix is sparse, this results in lots of largely useless rules\&.
.sp
These extra rules can be eliminated by setting the 1 bit in OPTIMIZE\&.
.sp
The 1 bit setting also controls the suppression of redundant wildcard rules (those specifying "all" in the SOURCE or DEST column)\&. A wildcard rule is considered to be redundant when it has the same ACTION and Log Level as the applicable policy\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
Optimization level 1 is ignored when optimization level 4 is also selected, since level 4 performs similar optimizations in a more robust way\&.
.sp .5v
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Optimization category 2 \- Added in Shorewall 4\&.4\&.7\&. When set, suppresses superfluous ACCEPT rules in a policy chain that implements an ACCEPT policy\&. Any ACCEPT rules that immediately precede the final blanket ACCEPT rule in the chain are now omitted\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Optimization category 4 \- Added in Shorewall 4\&.4\&.7\&. When set, causes short chains (those with less than 2 rules) to be optimized away\&. The following chains are excluded from optimization:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
accounting chains (unless OPTIMIZE_ACCOUNTING=Yes)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
action chains (user\-defined)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\*(Aqblacklst\*(Aq chain
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
dynamic
.RE
.sp
Additionally:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If a built\-in chain has a single rule that branches to a second chain, then the rules from the second chain are moved to the built\-in chain and the target chain is omitted\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Chains with no references are deleted\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Accounting chains are subject to optimization if the OPTIMIZE_ACCOUNTING option is set to \*(AqYes\*(Aq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If a chain ends with an unconditional branch to a second chain (other than to \*(Aqreject\*(Aq), then the branch is deleted from the first chain and the rules from the second chain are appended to it\&.
.RE
.sp
An additional optimization was added in Shorewall 4\&.5\&.4\&. If the last rule in a chain is an unqualified jump to a simple target, then all immediately preceding rules with the same simple target are omitted\&.
.sp
For example, consider this chain:
.sp
.if n \{\
.RS 4
.\}
.nf
	\-A fw\-net \-p udp \-\-dport 67:68 \-j ACCEPT
	\-A fw\-net \-p udp \-\-sport 1194 \-j ACCEPT
	\-A fw\-net \-p 41 \-j ACCEPT
	\-A fw\-net \-j ACCEPT
.fi
.if n \{\
.RE
.\}
.sp
Since all of the rules are jumps to the simple target ACCEPT, this chain is totally optimized away and jumps to the chain are replace with jumps to ACCEPT\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Optimization category 8 \- Added in Shorewall 4\&.4\&.9\&. When set, causes chains with identical rules to be collapsed into a single chain\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Optimization category 16 \- Added in Shorewall 4\&.4\&.26\&. When set, causes sequences of
compatible
rules to be combined into a single rule\&. Rules are considered compatible if they differ only in their destination ports and comments\&.
.sp
A sequence of compatible rules is often generated when macros are invoked in sequence\&.
.sp
The ability to combine adjacent rules is limited by two factors:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Destination port lists may only be combined up to a maximum of 15 ports, where a port\-pair counts as two ports\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Rules may only be combined until the length of their concatenated comment reaches 255 characters\&.
.RE
.sp
When either of these limits would be exceeded, the current combined rule is emitted and the compiler attempts to combine rules beginning with the one that would have exceeded the limit\&. Adjacent combined comments are separated by \*(Aq, \*(Aq\&. Empty comments at the front of a group of combined comments are replaced by \*(AqOthers and\*(Aq\&. Empty comments at the end of a group of combined comments are replaced by \*(Aqand others\*(Aq\&.
.sp
Beginning in Shorewall 4\&.5\&.10, this option also suppresses duplicate adjacent rules and duplicate non\-adjacent rules that don\*(Aqt include
\fBmark\fR,
\fBconnmark\fR,
\fBdscp\fR,
\fBecn\fR,
\fBset\fR,
\fBtos\fR
or
\fBu32\fR
matches\&.
.PP
Example 1:
.RS 4
Rules with comments "FOO", <empty> and "BAR" would result in the combined comment "FOO and others, BAR"\&.
.RE
.PP
Example 2:
.RS 4
Rules with comments <empty>, "FOO" and "BAR" would result in the combined comment "Others and FOO, BAR"\&. Note: Optimize level 16 requires "Extended Multi\-port Match" in your iptables and kernel\&.
.RE
.RE
.sp
The default value is zero which disables all optimizations\&.
.RE
.PP
\fBOPTIMIZE_ACCOUNTING=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Added in Shorewall 4\&.4\&.7\&. If set to Yes, Shorewall accounting changes are subject to optimization (OPTIMIZE=4,5,6 or 7)\&. If not specified or set to the empty value, OPTIMIZE_ACCOUNTING=No is assumed\&.
.RE
.PP
\fBPATH=\fR\fIpathname\fR[\fB:\fR\fIpathname\fR]\&.\&.\&.
.RS 4
Determines the order in which Shorewall6 searches directories for executable files\&.
.RE
.PP
\fBPERL=\fR\fIpathname\fR
.RS 4
Added in Shorewall 4\&.4\&.11 RC1\&. Specifies the path name of the Perl executable\&. Default is
/usr/bin/perl\&. If the pathname specified by this option does not exist or the named file is not executable, then Shorewall6 falls back to
/usr/bin/perl/
.RE
.PP
\fBPROVIDER_BITS\fR=[\fInumber\fR]
.RS 4
Added in Shorewall 4\&.4\&.26\&. The number of bits in the 32\-bit packet mark to be used for provider numbers\&. May be zero\&. See
MASK_BITS
above for default value\&.
.RE
.PP
\fBPROVIDER_OFFSET\fR=[\fInumber\fR]
.RS 4
Added in Shorewall 4\&.4\&.26\&. The offset from the right (low\-order end) of the provider number field in the 32\-bit packet mark\&. If non\-zero, must be >= TC_BITS (Shorewall automatically adjusts PROVIDER_OFFSET\*(Aqs value)\&. PROVIDER_OFFSET + PROVIDER_BITS + ZONE_BITS must be < 32\&. See
MASK_BITS
above for default value\&.
.RE
.PP
\fBRCP_COMMAND="\fR\fIcommand\fR\fB"\fR
.RS 4
.RE
.PP
\fBRSH_COMMAND="\fR\fIcommand\fR\fB"\fR
.RS 4
Earlier generations of Shorewall6 Lite required that remote root login via ssh be enabled in order to use the
\fBload\fR
and
\fBreload\fR
commands\&. Beginning with release 3\&.9\&.5, you may define an alternative means for accessing the remote firewall system\&. In that release, two new options were added to shorewall6\&.conf:.RS 4
RSH_COMMAND
.RE
.RS 4
RCP_COMMAND
.RE
The default values for these are as follows:.RS 4
RSH_COMMAND: ssh ${root}@${system} ${command}
.RE
.RS 4
RCP_COMMAND: scp ${files}
              ${root}@${system}:${destination}
.RE
Shell variables that will be set when the commands are invoked are as follows:.RS 4
\fIroot\fR \- root user\&. Normally
              \fBroot\fR but may be overridden using the \*(Aq\-r\*(Aq
              option\&.
.RE
.RS 4
\fIsystem\fR \- The name/IP address
              of the remote firewall system\&.
.RE
.RS 4
\fIcommand\fR \- For RSH_COMMAND,
              the command to be executed on the firewall system\&.
.RE
.RS 4
\fIfiles\fR \- For RCP_COMMAND, a
              space\-separated list of files to be copied to the remote
              firewall system\&.
.RE
.RS 4
\fIdestination\fR \- The directory
              on the remote system that the files are to be copied
              into\&.
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBRELATED_DISPOSITION=[ACCEPT|A_ACCEPT|A_DROP|A_REJECT|DROP|REJECT|CONTINUE]\fR
.RS 4
Added in Shorewall 4\&.4\&.27\&. Shorewall has traditionally ACCEPTed RELATED packets that don\*(Aqt match any rule in the RELATED section of
\m[blue]\fBshorewall6\-rules\fR\m[]\&\s-2\u[6]\d\s+2
(5)\&. Concern about the safety of this practice resulted in the addition of this option\&. When a packet in RELATED state fails to match any rule in the RELATED section, the packet is disposed of based on this setting\&. The default value is ACCEPT for compatibility with earlier versions\&.
.RE
.PP
\fBRELATED_LOG_LEVEL=\fR\fIlog\-level\fR
.RS 4
Added in Shorewall 4\&.4\&.27\&. Packets in the related state that do not match any rule in the RELATED section of
\m[blue]\fBshorewall6\-rules\fR\m[]\&\s-2\u[17]\d\s+2
(5) are logged at this level\&. The default value is empty which means no logging is performed\&.
.RE
.PP
\fBREJECT_ACTION=\fR\fIaction\fR
.RS 4
Added in Shorewall 4\&.5\&.21\&. When a REJECT target is specified, Shorewall normally handles the response as follows:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
If the destination address of the packet is a broadcast or multicast address, the packet is dropped\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
if the protocol is ICMP (58) then the packet is dropped\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
if the protocol is TCP (6) then the packet is rejected with an RST\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
if the protocol is UDP (17) then the packet is rejected with an \*(Aqport\-unreachable\*(Aq ICMP (ICMP6)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
if the protocol is ICMP (1) then the packet is rejected with a \*(Aqaddr\-unreachable\*(Aq ICMP\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
otherwise, the packet is rejected with a \*(Aqadm\-prohibited\*(Aq ICMP\&.
.RE
.sp
You can modify this behavior by implementing your own
\fIaction\fR
that handles REJECT and specifying it\*(Aqs name in this option\&. The
\fBnolog\fR
and
\fBinline\fR
options will automatically be assumed for the specified
\fIaction\fR\&.
.sp
The following action implements the standard behavior:
.sp
.if n \{\
.RS 4
.\}
.nf
?format 2
#TARGET         SOURCE  DEST    PROTO
Broadcast(DROP) \-       \-       \-
DROP            \-       \-       2
INLINE          \-       \-       6       ; \-j REJECT \-\-reject\-with tcp\-reset
?if __ENHANCED_REJECT
INLINE          \-       \-       17      ; \-j REJECT
?if __IPV4
INLINE          \-       \-       1       ; \-j REJECT \-\-reject\-with icmp\-host\-unreachable
INLINE          \-       \-       \-       ; \-j REJECT \-\-reject\-with icmp\-host\-prohibited
?else
INLINE          \-       \-       58      ; \-j REJECT \-\-reject\-with icmp6\-addr\-unreachable
INLINE          \-       \-       \-       ; \-j REJECT \-\-reject\-with icmp6\-adm\-prohibited
?endif
?else
INLINE          \-       \-       \-       ; \-j REJECT
?endif
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBREQUIRE_INTERFACE=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Added in Shorewall 4\&.4\&.10\&. The default is No\&. If set to Yes, at least one optional interface must be up in order for the firewall to be in the started state\&. Intended to be used with the
\m[blue]\fBShorewall Init Package\fR\m[]\&\s-2\u[18]\d\s+2\&.
.RE
.PP
\fBRESTORE_ROUTEMARKS=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Added in Shorewall 4\&.5\&.9\&. When set to
\fBYes\fR
(the default), provider marks are restored unconditionally at the top of the mangle OUTPUT and PREROUTING chains, even if the saved mark is zero\&. When this option is set to
\fBNo\fR, the mark is restored even when it is zero\&. If you have problems with IPSEC ESP packets not being routed correctly on output, try setting this option to
\fBNo\fR\&.
.RE
.PP
\fBRESTOREFILE=\fR\fIfilename\fR
.RS 4
Specifies the simple name of a file in /var/lib/shorewall6 to be used as the default restore script in the
\fBshorewall6 save\fR,
\fBshorewall6 restore\fR,
\fBshorewall6 forget \fRand
\fBshorewall6 \-f start\fR
commands\&.
.RE
.PP
\fBRPFILTER_DISPOSITION=\fR[\fBDROP\fR|\fBREJECT\fR|A_DROP|A_REJECT]
.RS 4
Added in Shorewall 4\&.5\&.7\&. Determines the disposition of packets entering from interfaces with the
\fBrpfilter\fR
option (see
\m[blue]\fBshorewall\-interfaces\fR\m[]\&\s-2\u[19]\d\s+2(5))\&. Packets disposed of by this option are those whose response packets would not be sent through the same interface receiving the packet\&.
.RE
.PP
\fBRPFILTER_LOG_LEVEL=\fR\fIlog\-level\fR
.RS 4
Added in shorewall 4\&.5\&.7\&. Determines the logging of packets disposed via the RPFILTER_DISPOSITION\&. The default value is
\fBinfo\fR\&.
.RE
.PP
\fBSHOREWALL_SHELL=\fR[\fIpathname\fR]
.RS 4
This option is used to specify the shell program to be used to interpret the compiled script\&. If not specified or specified as a null value, /bin/sh is assumed\&. Using a light\-weight shell such as ash or dash can significantly improve performance\&.
.RE
.PP
\fBSMURF_DISPOSITION=\fR[\fBDROP\fR|A_DROP]
.RS 4
Added in Shorewall 4\&.4\&.20\&. The default setting is DROP which causes smurf packets (see the nosmurfs option in
\m[blue]\fBshorewall\-interfaces\fR\m[]\&\s-2\u[19]\d\s+2(5)) to be dropped\&. A_DROP causes the packets to be audited prior to being dropped and requires AUDIT_TARGET support in the kernel and ip6tables\&.
.RE
.PP
\fBSMURF_LOG_LEVEL=\fR[\fIlog\-level\fR]
.RS 4
Specifies the logging level for smurf packets (see the nosmurfs option in
\m[blue]\fBshorewall6\-interfaces\fR\m[]\&\s-2\u[20]\d\s+2(5))\&. If set to the empty value ( SMURF_LOG_LEVEL="" ) then smurfs are not logged\&.
.RE
.PP
\fBSFILTER_DISPOSITION=\fR[\fBDROP\fR|\fBREJECT\fR|A_DROP|A_REJECT]
.RS 4
Added in Shorewall 4\&.4\&.20\&. Determines the disposition of packets matching the
\fBsfilter\fR
option (see
\m[blue]\fBshorewall6\-interfaces\fR\m[]\&\s-2\u[20]\d\s+2(5)) and of
hairpin
packets on interfaces without the
\fBrouteback\fR
option\&.\&\s-2\u[21]\d\s+2
interfaces without the routeback option\&.
.RE
.PP
\fBSFILTER_LOG_LEVEL=\fR\fIlog\-level\fR
.RS 4
Added on Shorewall 4\&.4\&.20\&. Determines the logging of packets matching the
\fBsfilter\fR
option (see
\m[blue]\fBshorewall6\-interfaces\fR\m[]\&\s-2\u[20]\d\s+2(5)) and of
hairpin
packets on interfaces without the
\fBrouteback\fR
option\&.\&\s-2\u[22]\d\s+2
interfaces without the routeback option\&. The default is
\fBinfo\fR\&. If you don\*(Aqt wish for these packets to be logged, use SFILTER_LOG_LEVEL=none\&.
.RE
.PP
\fBSTARTUP_ENABLED=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Determines if Shorewall6 is allowed to start\&. As released from shorewall\&.net, this option is set to
\fBNo\fR\&. When set to
\fBYes\fR
or
\fByes\fR, Shorewall6 may be started\&. Used as a guard against Shorewall6 being accidentally started before it has been configured\&.
.RE
.PP
\fBSTARTUP_LOG=\fR[\fIpathname\fR]
.RS 4
If specified, determines where Shorewall6 will log the details of each
\fBstart\fR,
\fBrestart\fR
and
\fBrefresh\fR
command\&. Logging verbosity is determined by the setting of LOG_VERBOSITY above\&.
.RE
.PP
\fBSUBSYSLOCK=\fR[\fIpathname\fR]
.RS 4
This parameter should be set to the name of a file that the firewall should create if it starts successfully and remove when it stops\&. Creating and removing this file allows Shorewall6 to work with your distribution\*(Aqs initscripts\&. For RedHat, this should be set to /var/lock/subsys/shorewall6\&. For Debian, the value is /var/lock/shorewall6 and in LEAF it is /var/run/shorewall\&.
.RE
.PP
\fBTC\fR=[\fIpathname\fR]
.RS 4
If specified, gives the pathname of the \*(Aqtc\*(Aq executable\&. If not specified, \*(Aqtc\*(Aq is assumed and the utility will be located using the current PATH setting\&.
.RE
.PP
\fBTC_BITS\fR=[\fInumber\fR]
.RS 4
Added in Shorewall 4\&.4\&.26\&. The number of bits at the low end of the 32\-bit packet mark to be used for traffic shaping marking\&. May be zero\&. See
MASK_BITS
above for default value\&.
.RE
.PP
\fBTC_ENABLED=\fR[\fBYes\fR|\fBNo\fR|\fBInternal|Shared\fR]
.RS 4
If you say
\fBYes\fR
or
\fByes\fR
here, Shorewall6 will use a script that you supply to configure traffic shaping\&. The script must be named \*(Aqtcstart\*(Aq and must be placed in a directory on your CONFIG_PATH\&.
.sp
If you say
\fBNo\fR
or
\fBno\fR
then traffic shaping is not enabled\&.
.sp
If you set TC_ENABLED=Internal or internal or leave the option empty then Shorewall6 will use its builtin traffic shaper (tc4shorewall6 written by Arne Bernin\&.
.sp
Beginning with Shorewall 4\&.4\&.15, if you set TC_ENABLED=Shared or shared, then you should create symbolic links from your Shorewall6 configuration directory (normally
/etc/shorewall6/) to your Shorewall
tcdevices
and
tcclasses
files\&. This allows the compiler to have access to your Shorewall traffic shaping configuration so that it can validate CLASSIFY rules in
\m[blue]\fBshorewall6\-tcrules\fR\m[]\&\s-2\u[23]\d\s+2
(5)\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBWarning\fR
.ps -1
.br
If you also run Shorewall and if you have TC_ENABLED=Internal in your
\m[blue]\fBshorewall\-conf\fR\m[]\&\s-2\u[10]\d\s+2(5), then you will want TC_ENABLED=No or TC_ENABLED=Shared in this file\&.
.sp .5v
.RE
.RE
.PP
\fBTC_EXPERT=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Normally, Shorewall6 tries to protect users from themselves by preventing PREROUTING and OUTPUT tcrules from being applied to packets that have been marked by the \*(Aqtrack\*(Aq option in
\m[blue]\fBshorewall6\-providers\fR\m[]\&\s-2\u[24]\d\s+2(5)\&.
.sp
If you know what you are doing, you can set TC_EXPERT=Yes and Shorewall6 will not include these cautionary checks\&.
.RE
.PP
\fBTC_PRIOMAP\fR=\fImap\fR
.RS 4
Added in Shorewall 4\&.4\&.6\&. Determines the mapping of a packet\*(Aqs TOS field to priority bands\&. See
\m[blue]\fBshorewall6\-tcpri\fR\m[]\&\s-2\u[25]\d\s+2(5)\&. The
\fImap\fR
consists of 16 space\-separated digits with values 1, 2 or 3\&. A value of 1 corresponds to Linux priority 0, 2 to Linux priority 1, and 3 to Linux Priority 2\&. The first entry gives the priority of TOS value 0, the second of TOS value 1, and so on\&. See tc\-prio(8) for additional information\&.
.sp
The default setting is TC_PRIOMAP="2 3 3 3 2 3 1 1 2 2 2 2 2 2 2 2"\&.
.RE
.PP
\fBTCP_FLAGS_DISPOSITION=\fR[\fBACCEPT\fR|\fBDROP\fR|\fBREJECT\fR]
.RS 4
Determines the disposition of TCP packets that fail the checks enabled by the
\fBtcpflags\fR
interface option (see
\m[blue]\fBshorewall6\-interfaces\fR\m[]\&\s-2\u[20]\d\s+2(5)) and must have a value of ACCEPT (accept the packet), REJECT (send an RST response) or DROP (ignore the packet)\&. If not set or if set to the empty value (e\&.g\&., TCP_FLAGS_DISPOSITION="") then TCP_FLAGS_DISPOSITION=DROP is assumed\&.
.RE
.PP
\fBTCP_FLAGS_LOG_LEVEL=\fR[\fIlog\-level\fR]
.RS 4
Determines the syslog level for logging packets that fail the checks enabled by the tcpflags interface option\&. The value must be a valid syslogd log level\&. If you don\*(Aqt want to log these packets, set to the empty value (e\&.g\&., TCP_FLAGS_LOG_LEVEL="")\&.
.RE
.PP
\fBTRACK_PROVIDERS=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Added in Shorewall 4\&.4\&.3\&. When set to Yes, causes the
\fBtrack\fR
option to be assumed on all providers defined in
\m[blue]\fBshorewall6\-providers\fR\m[]\&\s-2\u[24]\d\s+2(5)\&. May be overridden on an individual provider through use of the
\fBnotrack\fR
option\&. The default value is \*(AqNo\*(Aq\&.
.sp
Beginning in Shorewall 4\&.4\&.6, setting this option to \*(AqYes\*(Aq also simplifies PREROUTING rules in
\m[blue]\fBshorewall6\-tcrules\fR\m[]\&\s-2\u[9]\d\s+2(5)\&. Previously, when TC_EXPERT=No, packets arriving through \*(Aqtracked\*(Aq provider interfaces were unconditionally passed to the PREROUTING tcrules\&. This was done so that tcrules could reset the packet mark to zero, thus allowing the packet to be routed using the \*(Aqmain\*(Aq routing table\&. Using the main table allowed dynamic routes (such as those added for VPNs) to be effective\&. The
\m[blue]\fBshorewall6\-rtrules\fR\m[]\&\s-2\u[26]\d\s+2(5) file was created to provide a better alternative to clearing the packet mark\&. As a consequence, passing these packets to PREROUTING complicates things without providing any real benefit\&. Beginning with Shorewall 4\&.4\&.6, when TRACK_PROVIDERS=Yes and TC_EXPERT=No, packets arriving through \*(Aqtracked\*(Aq interfaces will not be passed to the PREROUTING rules\&. Since TRACK_PROVIDERS was just introduced in 4\&.4\&.3, this change should be transparent to most, if not all, users\&.
.RE
.PP
\fBTRACK_RULES=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Added in Shorewall 4\&.5\&.20\&. If set to
\fBYes\fR, causes the compiler to add a comment to iptables rules to indicate the file name and line number of the configuration entry that generated the rule\&. If set to
\fBNo\fR
(the default), then no such comments are added\&.
.sp
Setting this option to
\fBYes\fR
requires the
Comments
capability in ip6tables and kernel\&.
.RE
.PP
\fBUNTRACKED_DISPOSITION=[ACCEPT|A_ACCEPT|A_DROP|A_REJECT|DROP|REJECT|CONTINUE]\fR
.RS 4
Added in Shorewall 4\&.5\&.13\&. Shorewall has traditionally passed UNTRACKED packets through the NEW section of
\m[blue]\fBshorewall6\-rules\fR\m[]\&\s-2\u[6]\d\s+2
(5)\&. When a packet in UNTRACKED state fails to match any rule in the UNTRACKED section, the packet is disposed of based on this setting\&. The default value is CONTINUE for compatibility with earlier versions\&.
.RE
.PP
\fBUNTRACKED_LOG_LEVEL=\fR\fIlog\-level\fR
.RS 4
Added in Shorewall 4\&.5\&.13\&. Packets in the UNTRACKED state that do not match any rule in the UNTRACKED section of
\m[blue]\fBshorewall\-rules\fR\m[]\&\s-2\u[17]\d\s+2
(5) are logged at this level\&. The default value is empty which means no logging is performed\&.
.RE
.PP
\fBUSE_DEFAULT_RT=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Added in Shorewall6 4\&.4\&.25\&. When set to \*(AqYes\*(Aq, this option causes the Shorewall6 multi\-ISP feature to create a different set of routing rules which are resilient to changes in the main routing table\&. Such changes can occur for a number of reasons, VPNs going up and down being an example\&. The idea is to send packets through the main table prior to applying any of the Shorewall6\-generated routing rules\&. So changes to the main table will affect the routing of packets by default\&.
.sp
When USE_DEFAULT_RT=Yes:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Both the DUPLICATE and the COPY columns in
\m[blue]\fBshorewall6\-providers\fR\m[]\&\s-2\u[24]\d\s+2(5) file must remain empty (or contain "\-")\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
The default route is added to the the \*(Aqdefault\*(Aq table rather than to the main table\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
\fBbalance\fR
is assumed unless
\fBloose\fR
is specified\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Packets are sent through the main routing table by a rule with priority 999\&. In
\m[blue]\fBshorewall6\-routing_rules\fR\m[]\&\s-2\u[27]\d\s+2(5), the range 1\-998 may be used for inserting rules that bypass the main table\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 5.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  5." 4.2
.\}
All provider gateways must be specified explicitly in the GATEWAY column\&.
\fBdetect\fR
may not be specified\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 6.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  6." 4.2
.\}
You should disable all default route management outside of Shorewall6\&. If a default route is added to the main table while Shorewall is started, then all policy routing will stop working (except for those routing rules in the priority range 1\-998)\&.
.RE
.sp
If USE_DEFAULT_RT is not set or if it is set to the empty string then USE_DEFAULT_RT=No is assumed\&.
.RE
.PP
\fBUSE_PHYSICAL_NAMES=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Added in Shorewall 4\&.4\&.27\&. Normally, when Shorewall creates a Netfilter chain that relates to an interface, it uses the interface\*(Aqs logical name as the base of the chain name\&. For example, if the logical name for an interface is OAKLAND, then the input chain for traffic arriving on that interface would be \*(AqOAKLAND_in\*(Aq\&. If this option is set to Yes, then the physical name of the interface will be used the base of the chain name\&.
.RE
.PP
\fBUSE_RT_NAMES=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Added in Shorewall 4\&.5\&.15\&. When set to \*(AqYes\*(Aq, Shorewall will use routing table (provider) names in the generated script rather than table numbers\&. When set to \*(AqNo\*(Aq (the default), routing table numbers will be used\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBCaution\fR
.ps -1
.br
If you set USE_RT_NAMES=Yes and KEEP_RT_TABLES=Yes, then you must insure that all of your providers have entries in /etc/iproute2/rt_tables as well as the following entries:
.RS 4
255 local
.RE
.RS 4
254 main
.RE
.RS 4
253 default
.RE
.RS 4
250 balance
.RE
.RS 4
0 unspec
.RE
Without these entries, the firewall will fail to start\&.
.sp .5v
.RE
.RE
.PP
\fBVERBOSITY=\fR[\fInumber\fR]
.RS 4
Shorewall6 has traditionally been very noisy (produced lots of output)\&. You may set the default level of verbosity using the VERBOSITY OPTION\&.
.sp
Values are:
.RS 4
0 \- Silent\&. You may make it more verbose using the \-v
            option
.RE
.RS 4
1 \- Major progress messages displayed
.RE
.RS 4
2 \- All progress messages displayed (pre Shorewall6\-3\&.2\&.0
            behavior)
.RE
If not specified, then 2 is assumed\&.
.RE
.PP
\fBWARNOLDCAPVERSION=\fR[\fBYes\fR|\fBNo\fR]
.RS 4
Added in Shorewall 4\&.5\&.12\&. When set to
\fBYes\fR
(the default), the compiler issues a warning when it finds a capabilities file that doesn\*(Aqt specify all of the capabilities supported by the compiler\&. When WARNOLDCAPVERSION is set to
\fBNo\fR, no warning is issued\&.
.RE
.PP
\fBWIDE_TC_MARKS=\fR{\fBYes\fR|\fBNo\fR}
.RS 4
Deprecated in Shorewall 4\&.4\&.26 in favor of TC_BITS and MASK_BITS\&.
.sp
When set to No (the default), traffic shaping marks are 8 bytes wide (possible values are 1\-255)\&. When WIDE_TC_MARKS=Yes, traffic shaping marks are 14 bytes wide (values 1\-16383)\&. The setting of WIDE_TC_MARKS also has an effect on the HIGH_ROUTE_MARKS option (see above)\&.
.RE
.PP
\fBZONE_BITS\fR=[\fInumber\fR]
.RS 4
Added in Shorewall 4\&.4\&.26\&. When non\-zero, enables automatic packet marking by source zone and determines the number of bits in the 32\-bit packet mark to be used for the zone mark\&. Default value is 0\&.
.RE
.PP
\fBZONE2ZONE\fR={\fB2\fR|\fB\-\fR}
.RS 4
Added in Shorewall 4\&.4\&.4\&. This option determines how Shorewall constructs chain names involving zone names and/or \*(Aqall\*(Aq\&. The default is \*(Aq2\*(Aq (e\&.g\&., fw2net)\&.
.RE
.SH "FILES"
.PP
/etc/shorewall6/shorewall6\&.conf
.SH "SEE ALSO"
.PP
shorewall6(8), shorewall6\-accounting(5), shorewall6\-actions(5), shorewall6\-blacklist(5), shorewall6\-hosts(5), shorewall6\-interfaces(5), shorewall6\-ipsec(5), shorewall6\-maclist(5), shorewall6\-masq(5), shorewall6\-nat(5), shorewall6\-netmap(5), shorewall6\-netmap(5),shorewall6\-params(5), shorewall6\-policy(5), shorewall6\-providers(5), shorewall6\-proxyarp(5), shorewall6\-rtrules(5), shorewall6\-routestopped(5), shorewall6\-rules(5), shorewall6\-tcclasses(5), shorewall6\-tcdevices(5), shorewall6\-tcrules(5), shorewall6\-tos(5), shorewall6\-tunnels(5), shorewall6\-zones(5)
.SH "NOTES"
.IP " 1." 4
shorewall6-policy
.RS 4
\%http://www.shorewall.net/manpages6/shorewall6-policy.html
.RE
.IP " 2." 4
shorewall6-accounting
.RS 4
\%http://www.shorewall.net/manpages6/shorewall6-accounting.html
.RE
.IP " 3." 4
shorewall-accounting
.RS 4
\%http://www.shorewall.net/manpages6/shorewall-accounting.html
.RE
.IP " 4." 4
shorewall6-routestopped
.RS 4
\%http://www.shorewall.net/manpages6/shorewall6-routestopped.html
.RE
.IP " 5." 4
shorewall6-conntrack
.RS 4
\%http://www.shorewall.net/manpages6/shorewall-conntrack.html
.RE
.IP " 6." 4
shorewall6-rules
.RS 4
\%http://www.shorewall.net/manpages6/shorewall6-rules.html
.RE
.IP " 7." 4
shorewall6-blrules
.RS 4
\%http://www.shorewall.net/manpages6/shorewall6-blrules.html
.RE
.IP " 8." 4
shorewall6-conntrack
.RS 4
\%http://www.shorewall.net/manpages6/shorewall6-conntrack.html
.RE
.IP " 9." 4
shorewall6-tcrules
.RS 4
\%http://www.shorewall.net/manpages6/shorewall6-tcrules.html
.RE
.IP "10." 4
shorewall-conf
.RS 4
\%http://www.shorewall.net/manpages6/../manpages/shorewall.conf.html
.RE
.IP "11." 4
shorewall6-zones
.RS 4
\%http://www.shorewall.net/manpages6/shorewall6-zones.html
.RE
.IP "12." 4
shorewall6-nesting
.RS 4
\%http://www.shorewall.net/manpages6/shorewall6-nesting.html
.RE
.IP "13." 4
shorewall-rules
.RS 4
\%http://www.shorewall.net/manpages6/manpages/shorewall6-rules.html
.RE
.IP "14." 4
shorewall-maclist
.RS 4
\%http://www.shorewall.net/manpages6/shorewall-maclist.html
.RE
.IP "15." 4
shorewall.conf
.RS 4
\%http://www.shorewall.net/manpages6/shorewall.conf.html
.RE
.IP "16." 4
the complete matrix of host groups defined by the zones, interfaces and hosts files
.RS 4
\%http://www.shorewall.net/manpages6/../ScalabilityAndPerformance.html
.RE
.IP "17." 4
shorewall6-rules
.RS 4
\%http://www.shorewall.net/manpages6/manpages/shorewall-rules.html
.RE
.IP "18." 4
Shorewall Init Package
.RS 4
\%http://www.shorewall.net/manpages6/../Manpages/shorewall-init.html
.RE
.IP "19." 4
shorewall-interfaces
.RS 4
\%http://www.shorewall.net/manpages6/shorewall-interfaces.html
.RE
.IP "20." 4
shorewall6-interfaces
.RS 4
\%http://www.shorewall.net/manpages6/shorewall6-interfaces.html
.RE
.IP "21." 4
Hairpin packets are packets that are routed out of the same interface that they arrived on.
.IP "22." 4
Hairpin packets are packets that are routed out of the same interface that they arrived on.
.IP "23." 4
shorewall6-tcrules
.RS 4
\%http://www.shorewall.net/manpages6/shorewall-tcrules.html
.RE
.IP "24." 4
shorewall6-providers
.RS 4
\%http://www.shorewall.net/manpages6/shorewall6-providers.html
.RE
.IP "25." 4
shorewall6-tcpri
.RS 4
\%http://www.shorewall.net/manpages6/shorewall6-tcpri.html
.RE
.IP "26." 4
shorewall6-rtrules
.RS 4
\%http://www.shorewall.net/manpages6/shorewall6-rtrules.html
.RE
.IP "27." 4
shorewall6-routing_rules
.RS 4
\%http://www.shorewall.net/manpages6/shorewall6-routing_rules.html
.RE
