.\"     Title: shorewall-lite
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/05/2010
.\"    Manual: 
.\"    Source: 
.\"
.TH "SHOREWALL\-LITE" "8" "07/05/2010" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
shorewall-lite \- Administration tool for Shoreline Firewall Lite (Shorewall-lite)
.SH "SYNOPSIS"
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR\ [\fBnolock\fR]] [\-\fIoptions\fR] \fBallow\fR \fIaddress\fR
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR\ [\fBnolock\fR]] [\-\fIoptions\fR] \fBclear\fR
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR\ [\fBnolock\fR]] [\-\fIoptions\fR] \fBdrop\fR \fIaddress\fR
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBdump\fR [\fB\-x\fR] [\fB\-m\fR]
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBforget\fR [\fIfilename\fR]
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBhelp\fR
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBhits\fR
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBipcalc\fR {\fIaddress\fR\ \fImask\fR | \fIaddress\fR/\fIvlsm\fR}
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBiprange\fR \fIaddress1\fR\fB\-\fR\fIaddress2\fR
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR\ [\fBnolock\fR]] [\-\fIoptions\fR] \fBlogdrop\fR \fIaddress\fR
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBlogwatch\fR [\fB\-m\fR] [\fIrefresh\-interval\fR]
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR\ [\fBnolock\fR]] [\-\fIoptions\fR] \fBlogreject\fR \fIaddress\fR
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR\ [\fBnolock\fR]] [\-\fIoptions\fR] \fBreject\fR \fIaddress\fR
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR\ [\fBnolock\fR]] [\-\fIoptions\fR] \fBrestart\fR\ [\fB\-n\fR]\ [\fB\-p\fR] 
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR\ [\fBnolock\fR]] [\-\fIoptions\fR] \fBrestore\fR [\fIfilename\fR]
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR\ [\fBnolock\fR]] [\-\fIoptions\fR] \fBsave\fR [\fIfilename\fR]
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBshow\fR [\fB\-x\fR] [\fB\-t\fR\ {\fBfilter\fR|\fBmangle\fR|\fBnat\fR|\fBraw\fR}] [[\fBchain\fR]\ \fIchain\fR...]
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBshow\fR [\fB\-f\fR] \fBcapabilities\fR
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBshow\fR {\fBactions|classifiers|connections|config|zones\fR}
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBshow\fR [\fB\-x\fR] {\fBmangle|nat\fR}
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBshow\fR \fBtc\fR
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBshow\fR [\fB\-m\fR] \fBlog\fR
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR\ [\fBnolock\fR]] [\-\fIoptions\fR] \fBstart\fR [\fB\-n\fR] [\fB\-f\fR\ [\fB\-p\fR]]
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR\ [\fBnolock\fR]] [\-\fIoptions\fR] \fBstop\fR
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBstatus\fR
.HP 15
\fBshorewall\-lite\fR [\fBtrace\fR|\fBdebug\fR] [\-\fIoptions\fR] \fBversion\fR
.SH "DESCRIPTION"
.PP
The shorewall\-lite utility is used to control the Shoreline Firewall (Shorewall) Lite\&.
.SH "OPTIONS"
.PP
The
\fBtrace\fR
and
\fBdebug\fR
options are used for debugging\&. See
\fIhttp://www\&.shorewall\&.net/starting_and_stopping\&.htm#Trace\fR\&.
.PP
The nolock
\fBoption\fR
prevents the command from attempting to acquire the Shorewall Lite lockfile\&. It is useful if you need to include
\fBshorewall\-lite\fR
commands in the
\fIstarted\fR
extension script\&.
.PP
The
\fIoptions\fR
control the amount of output that the command produces\&. They consist of a sequence of the letters
\fBv\fR
and
\fBq\fR\&. If the options are omitted, the amount of output is determined by the setting of the VERBOSITY parameter in
\fIshorewall\&.conf\fR\&[1](5)\&. Each
\fBv\fR
adds one to the effective verbosity and each
\fBq\fR
subtracts one from the effective VERBOSITY\&. Anternately,
\fBv\fR
may be followed immediately with one of \-1,0,1,2 to specify a specify VERBOSITY\&. There may be no white space between
\fBv\fR
and the VERBOSITY\&.
.PP
The
\fIoptions\fR
may also include the letter
\fBt\fR
which causes all progress messages to be timestamped\&.
.SH "COMMANDS"
.PP
The available commands are listed below\&.
.PP
\fBadd\fR
.RS 4
Adds a list of hosts or subnets to a dynamic zone usually used with VPN\'s\&.
.sp
The
\fIinterface\fR
argument names an interface defined in the
\fIshorewall\-interfaces\fR\&[2](5) file\&. A
\fIhost\-list\fR
is comma\-separated list whose elements are a host or network address\&..sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Caution
The
\fBadd\fR
command is not very robust\&. If there are errors in the
\fIhost\-list\fR, you may see a large number of error messages yet a subsequent
\fBshorewall show zones\fR
command will indicate that all hosts were added\&. If this happens, replace
\fBadd\fR
by
\fBdelete\fR
and run the same command again\&. Then enter the correct command\&.

.RE
.PP
\fBallow\fR
.RS 4
Re\-enables receipt of packets from hosts previously blacklisted by a
\fBdrop\fR,
\fBlogdrop\fR,
\fBreject\fR, or
\fBlogreject\fR
command\&.
.RE
.PP
\fBclear\fR
.RS 4
Clear will remove all rules and chains installed by Shorewall Lite\&. The firewall is then wide open and unprotected\&. Existing connections are untouched\&. Clear is often used to see if the firewall is causing connection problems\&.
.RE
.PP
\fBdelete\fR
.RS 4
The delete command reverses the effect of an earlier
\fBadd\fR
command\&.
.sp
The
\fIinterface\fR
argument names an interface defined in the
\fIshorewall\-interfaces\fR\&[2](5) file\&. A
\fIhost\-list\fR
is comma\-separated list whose elements are a host or network address\&.
.RE
.PP
\fBdrop\fR
.RS 4
Causes traffic from the listed
\fIaddress\fRes to be silently dropped\&.
.RE
.PP
\fBdump\fR
.RS 4
Produces a verbose report about the firewall configuration for the purpose of problem analysis\&.
.sp
The
\fB\-x\fR
option causes actual packet and byte counts to be displayed\&. Without that option, these counts are abbreviated\&. The
\fB\-m\fR
option causes any MAC addresses included in Shorewall Lite log messages to be displayed\&.
.RE
.PP
\fBforget\fR
.RS 4
Deletes /var/lib/shorewall\-lite/\fIfilenam\fRe and /var/lib/shorewall\-lite/save\&. If no
\fIfilename\fR
is given then the file specified by RESTOREFILE in
\fIshorewall\-lite\&.conf\fR\&[3](5) is assumed\&.
.RE
.PP
\fBhelp\fR
.RS 4
Displays a syntax summary\&.
.RE
.PP
\fBhits\fR
.RS 4
Generates several reports from Shorewall Lite log messages in the current log file\&.
.RE
.PP
\fBipcalc\fR
.RS 4
Ipcalc displays the network address, broadcast address, network in CIDR notation and netmask corresponding to the input[s]\&.
.RE
.PP
\fBiprange\fR
.RS 4
Iprange decomposes the specified range of IP addresses into the equivalent list of network/host addresses\&.
.RE
.PP
\fBlogdrop\fR
.RS 4
Causes traffic from the listed
\fIaddress\fRes to be logged then discarded\&.
.RE
.PP
\fBlogwatch\fR
.RS 4
Monitors the log file specified by theLOGFILE option in
\fIshorewall\-lite\&.conf\fR\&[3](5) and produces an audible alarm when new Shorewall Lite messages are logged\&. The
\fB\-m\fR
option causes the MAC address of each packet source to be displayed if that information is available\&. The
\fIrefresh\-interval\fR
specifies the time in seconds between screen refreshes\&. You can enter a negative number by preceding the number with "\-\-" (e\&.g\&.,
\fBshorewall\-lite logwatch \-\- \-30\fR)\&. In this case, when a packet count changes, you will be prompted to hit any key to resume screen refreshes\&.
.RE
.PP
\fBlogreject\fR
.RS 4
Causes traffic from the listed
\fIaddress\fRes to be logged then rejected\&.
.RE
.PP
\fBreset\fR
.RS 4
All the packet and byte counters in the firewall are reset\&.
.RE
.PP
\fBrestart\fR
.RS 4
Restart is similar to
\fBshorewall\-lite start\fR
but assumes that the firewall is already started\&. Existing connections are maintained\&.
.sp
The
\fB\-n\fR
option causes Shorewall to avoid updating the routing table(s)\&.
.sp
The
\fB\-p\fR
option causes the connection tracking table to be flushed; the
\fBconntrack\fR
utility must be installed to use this option\&.
.RE
.PP
\fBrestore\fR
.RS 4
Restore Shorewall Lite to a state saved using the
\fBshorewall\-lite save\fR
command\&. Existing connections are maintained\&. The
\fIfilename\fR
names a restore file in /var/lib/shorewall\-lite created using
\fBshorewall\-lite save\fR; if no
\fIfilename\fR
is given then Shorewall Lite will be restored from the file specified by the RESTOREFILE option in
\fIshorewall\-lite\&.conf\fR\&[3](5)\&.
.RE
.PP
\fBsave\fR
.RS 4
The dynamic blacklist is stored in /var/lib/shorewall\-lite/save\&. The state of the firewall is stored in /var/lib/shorewall\-lite/\fIfilename\fR
for use by the
\fBshorewall\-lite restore\fR
and
\fBshorewall\-lite \-f start\fR
commands\&. If
\fIfilename\fR
is not given then the state is saved in the file specified by the RESTOREFILE option in
\fIshorewall\-lite\&.conf\fR\&[3](5)\&.
.RE
.PP
\fBshow\fR
.RS 4
The show command can have a number of different arguments:
.PP
\fBactions\fR
.RS 4
Produces a report about the available actions (built\-in, standard and user\-defined)\&.
.RE
.PP
\fBcapabilities\fR
.RS 4
Displays your kernel/iptables capabilities\&. The
\fB\-f\fR
option causes the display to be formatted as a capabilities file for use with
\fBcompile \-e\fR\&.
.RE
.PP
[ [ \fBchain\fR ] \fIchain\fR \&.\&.\&. ]
.RS 4
The rules in each
\fIchain\fR
are displayed using the
\fBiptables \-L\fR
\fIchain\fR
\fB\-n \-v\fR
command\&. If no
\fIchain\fR
is given, all of the chains in the filter table are displayed\&. The
\fB\-x\fR
option is passed directly through to iptables and causes actual packet and byte counts to be displayed\&. Without this option, those counts are abbreviated\&. The
\fB\-t\fR
option specifies the Netfilter table to display\&. The default is
\fBfilter\fR\&.
.sp
If the
\fBt\fR
option and the
\fBchain\fR
keyword are both omitted and any of the listed
\fIchain\fRs do not exist, a usage message will be displayed\&.
.RE
.PP
\fBclassifiers\fR
.RS 4
Displays information about the packet classifiers defined on the system 10\-080213\-8397as a result of traffic shaping configuration\&.
.RE
.PP
\fBconfig\fR
.RS 4
Dispays distribution\-specific defaults\&.
.RE
.PP
\fBconnections\fR
.RS 4
Displays the IP connections currently being tracked by the firewall\&.
.RE
.PP
\fBmangle\fR
.RS 4
Displays the Netfilter mangle table using the command
\fBiptables \-t mangle \-L \-n \-v\fR\&.The
\fB\-x\fR
option is passed directly through to iptables and causes actual packet and byte counts to be displayed\&. Without this option, those counts are abbreviated\&.
.RE
.PP
\fBnat\fR
.RS 4
Displays the Netfilter nat table using the command
\fBiptables \-t nat \-L \-n \-v\fR\&.The
\fB\-x\fR
option is passed directly through to iptables and causes actual packet and byte counts to be displayed\&. Without this option, those counts are abbreviated\&.
.RE
.PP
\fBtc\fR
.RS 4
Displays information about queuing disciplines, classes and filters\&.
.RE
.PP
\fBzones\fR
.RS 4
Displays the current composition of the Shorewall Lite zones on the system\&.
.RE
.RE
.PP
\fBstart\fR
.RS 4
Start shorewall Lite\&. Existing connections through shorewall\-lite managed interfaces are untouched\&. New connections will be allowed only if they are allowed by the firewall rules or policies\&. If
\fB\-f\fR
is specified, the saved configuration specified by the RESTOREFILE option in
\fIshorewall\-lite\&.conf\fR\&[3](5) will be restored if that saved configuration exists and has been modified more recently than the files in /etc/shorewall\&.
.sp
The
\fB\-n\fR
option causes Shorewall to avoid updating the routing table(s)\&.
.sp
The
\fB\-p\fR
option causes the connection tracking table to be flushed; the
\fBconntrack\fR
utility must be installed to use this option\&.
.RE
.PP
\fBstop\fR
.RS 4
Stops the firewall\&. All existing connections, except those listed in
\fIshorewall\-routestopped\fR\&[4](5) or permitted by the ADMINISABSENTMINDED option in shorewall\&.conf(5), are taken down\&. The only new traffic permitted through the firewall is from systems listed in
\fIshorewall\-routestopped\fR\&[4](5) or by ADMINISABSENTMINDED\&.
.RE
.PP
\fBstatus\fR
.RS 4
Produces a short report about the state of the Shorewall\-configured firewall\&.
.RE
.PP
\fBversion\fR
.RS 4
Displays Shorewall\-lite\'s version\&.
.RE
.SH "FILES"
.PP
/etc/shorewall\-lite/
.SH "SEE ALSO"
.PP
\fIhttp://www\&.shorewall\&.net/starting_and_stopping_shorewall\&.htm\fR
.PP
shorewall\-accounting(5), shorewall\-actions(5), shorewall\-blacklist(5), shorewall\-hosts(5), shorewall\-interfaces(5), shorewall\-ipsec(5), shorewall\-maclist(5), shorewall\-masq(5), shorewall\-nat(5), shorewall\-netmap(5), shorewall\-params(5), shorewall\-policy(5), shorewall\-providers(5), shorewall\-proxyarp(5), shorewall\-route_rules(5), shorewall\-routestopped(5), shorewall\-rules(5), shorewall\&.conf(5), shorewall\-tcclasses(5), shorewall\-tcdevices(5), shorewall\-tcrules(5), shorewall\-tos(5), shorewall\-tunnels(5), shorewall\-zones(5)
.SH "NOTES"
.IP " 1." 4
shorewall.conf
.RS 4
\%shorewall.conf.html
.RE
.IP " 2." 4
shorewall-interfaces
.RS 4
\%shorewall-interfaces.html
.RE
.IP " 3." 4
shorewall-lite.conf
.RS 4
\%shorewall-lite.conf.html
.RE
.IP " 4." 4
shorewall-routestopped
.RS 4
\%shorewall-routestopped.html
.RE
