'\" t
.\"     Title: shorewall-tos
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 01/30/2014
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "SHOREWALL\-TOS" "5" "01/30/2014" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
tos \- Shorewall Type of Service rules file
.SH "SYNOPSIS"
.HP \w'\fB/etc/shorewall/tos\fR\ 'u
\fB/etc/shorewall/tos\fR
.SH "DESCRIPTION"
.PP
This file defines rules for setting Type Of Service (TOS)\&. Its use is deprecated, beginning in Shorewall 4\&.5\&.1, in favor of the TOS target in
\m[blue]\fBshorewall\-tcrules\fR\m[]\&\s-2\u[1]\d\s+2
(5)\&.
.PP
The columns in the file are as follows (where the column name is followed by a different name in parentheses, the different name is used in the alternate specification syntax)\&.
.PP
\fBSOURCE\fR \- {\fBall\fR|\fIaddress\fR]|\fBall\fR:\fIaddress\fR|\fB$FW\fR}
.RS 4
If
\fBall\fR, may optionally be followed by ":" and an IP address, a MAC address, a subnet specification or the name of an interface\&.
.sp
Example: all:192\&.168\&.2\&.3
.sp
MAC addresses must be prefixed with "~" and use "\-" as a separator\&.
.sp
Example: ~00\-A0\-C9\-15\-39\-78
.RE
.PP
\fBDEST\fR \- {\fBall\fR|\fIaddress\fR]|\fBall\fR:\fIaddress\fR}
.RS 4
Example: 192\&.168\&.2\&.3
.RE
.PP
\fBPROTOCOL\fR (proto) \- \fIproto\-name\-or\-number\fR
.RS 4
Protocol name or number\&.
.RE
.PP
\fBSOURCE PORT(S)\fR (sport) \- {\-|\fIport\fR|\fIlowport\fR\fB:\fR\fIhighport\fR}
.RS 4
Source port or port range\&. If all ports, use "\-"\&.
.RE
.PP
\fBDEST PORT(S)\fR (dport) \- {\-|\fIport\fR|\fIlowport\fR\fB:\fR\fIhighport\fR}
.RS 4
Destination port or port range\&. If all ports, use "\-"
.RE
.PP
\fBTOS\fR \- \fItos\fR
.RS 4
Must may one of the following;
.sp
.if n \{\
.RS 4
.\}
.nf
        \fBtos\-minimize\-delay\fR (16)
        \fBtos\-maximize\-throughput\fR (8)
        \fBtos\-maximize\-reliability\fR (4)
        \fBtos\-minimize\-cost\fR (2)
        \fBtos\-normal\-service\fR (0)
.fi
.if n \{\
.RE
.\}
.sp
To specify more than one flag, add their values together and specify the numeric result\&.
.RE
.PP
\fBMARK\fR \- [\fB!\fR]\fIvalue\fR[/\fImask\fR][\fB:C\fR]
.RS 4
If you don\*(Aqt want to define a test but need to specify anything in the following columns, place a "\-" in this field\&.
.PP
!
.RS 4
Inverts the test (not equal)
.RE
.PP
\fIvalue\fR
.RS 4
Value of the packet or connection mark\&.
.RE
.PP
\fImask\fR
.RS 4
A mask to be applied to the mark before testing\&.
.RE
.PP
\fB:C\fR
.RS 4
Designates a connection mark\&. If omitted, the packet mark\*(Aqs value is tested\&.
.RE
.RE
.SH "FILES"
.PP
/etc/shorewall/tos
.SH "SEE ALSO"
.PP
\m[blue]\fBhttp://shorewall\&.net/configuration_file_basics\&.htm#Pairs\fR\m[]
.PP
shorewall(8), shorewall\-accounting(5), shorewall\-actions(5), shorewall\-blacklist(5), shorewall\-hosts(5), shorewall_interfaces(5), shorewall\-ipsets(5), shorewall\-maclist(5), shorewall\-masq(5), shorewall\-nat(5), shorewall\-netmap(5), shorewall\-params(5), shorewall\-policy(5), shorewall\-providers(5), shorewall\-proxyarp(5), shorewall\-rtrules(5), shorewall\-routestopped(5), shorewall\-rules(5), shorewall\&.conf(5), shorewall\-secmarks(5), shorewall\-tcclasses(5), shorewall\-tcdevices(5), shorewall\-tcrules(5), shorewall\-tunnels(5), shorewall\-zones(5)
.SH "NOTES"
.IP " 1." 4
shorewall-tcrules
.RS 4
\%http://www.shorewall.netshorewall-tcrules.html
.RE
