.\"     Title: shorewall-netmap
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/23/2010
.\"    Manual: 
.\"    Source: 
.\"
.TH "SHOREWALL\-NETMAP" "5" "04/23/2010" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
netmap \- Shorewall NETMAP definition file
.SH "SYNOPSIS"
.HP 22
\fB/etc/shorewall/netmap\fR
.SH "DESCRIPTION"
.PP
This file is used to map addresses in one network to corresponding addresses in a second network\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Warning
.PP
To use this file, your kernel and iptables must have NETMAP support included\&.
.PP
The columns in the file are as follows\&.
.PP
\fBTYPE\fR \- \fBDNAT\fR|\fBSNAT\fR
.RS 4
Must be DNAT or SNAT\&.
.sp
If DNAT, traffic entering INTERFACE and addressed to NET1 has its destination address rewritten to the corresponding address in NET2\&.
.sp
If SNAT, traffic leaving INTERFACE with a source address in NET1 has it\'s source address rewritten to the corresponding address in NET2\&.
.RE
.PP
\fBNET1\fR \- \fInetwork\-address\fR
.RS 4
Network in CIDR format (e\&.g\&., 192\&.168\&.1\&.0/24)\&.
.RE
.PP
\fBINTERFACE\fR \- \fIinterface\fR
.RS 4
The name of a network interface\&. The interface must be defined in
\fIshorewall\-interfaces\fR\&[1](5)\&. Shorewall allows loose matches to wildcard entries in
\fIshorewall\-interfaces\fR\&[1](5)\&. For example,
\fIppp0\fR
in this file will match a
\fIshorewall\-interfaces\fR\&[1](8) entry that defines
\fIppp+\fR\&.
.RE
.PP
\fBNET2\fR \- \fInetwork\-address\fR
.RS 4
Network in CIDR format
.RE
.SH "FILES"
.PP
/etc/shorewall/netmap
.SH "SEE ALSO"
.PP
\fIhttp://shorewall\&.net/netmap\&.html\fR
.PP
shorewall(8), shorewall\-accounting(5), shorewall\-actions(5), shorewall\-blacklist(5), shorewall\-hosts(5), shorewall\-interfaces(5), shorewall\-ipsec(5), shorewall\-maclist(5), shorewall\-masq(5), shorewall\-nat(5), shorewall\-params(5), shorewall\-policy(5), shorewall\-providers(5), shorewall\-proxyarp(5), shorewall\-route_rules(5), shorewall\-routestopped(5), shorewall\-rules(5), shorewall\&.conf(5), shorewall\-tcclasses(5), shorewall\-tcdevices(5), shorewall\-tcrules(5), shorewall\-tos(5), shorewall\-tunnels(5), shorewall\-zones(5)
.SH "NOTES"
.IP " 1." 4
shorewall-interfaces
.RS 4
\%shorewall-interfaces.html
.RE
