#!/bin/sh -e

case "$1" in
    upgrade)
        # if we are upgrading from version < 3.4 then we have to rename the
        # configuration file
        if [ "$2" ] && dpkg --compare-versions "$2" lt "3.4"
        then
            if [ -f /etc/shorewall6-lite/shorewall.conf ]
            then
                ln /etc/shorewall6-lite/shorewall.conf /etc/shorewall6-lite/shorewall6-lite.conf
            fi
        fi
        ;;
    *)
        ;;
esac

#DEBHELPER#
